operaton/operaton

- pom.xml
Configure skipIfEmpty flag for maven-jar-plugin
Fixes #25
> Skip JAR creation when it would be empty

- connect/http-client/pom.xml
- connect/pom.xml
- connect/soap-http-client/pom.xml
- connect/soap-http-client/src/test/java/org/operaton/connect/soap/httpclient/SoapHttpConnectorSystemPropertiesTest.java
- engine-rest/engine-rest-openapi/pom.xml
- engine/pom.xml
- internal-dependencies/pom.xml
- parent/pom.xml
- qa/integration-tests-engine-jakarta/pom.xml
- qa/test-old-engine/pom.xml
Upgrade from `com.github.tomakehurst:wiremock:2.27.2` to `org.wiremock:wiremock:3.9.2`.
Fixes #46
> [deps] Upgrade Wiremock to version 3.9.2

- commons/pom.xml
- connect/pom.xml
- distro/run/qa/pom.xml
- freemarker-template-engine/pom.xml
- internal-dependencies/pom.xml
- parent/pom.xml
- spin/dataformat-all/pom.xml
- spring-boot-starter/starter-qa/integration-test-webapp/runtime/pom.xml
- test-utils/assert/core/pom.xml
- test-utils/assert/qa/pom.xml
- test-utils/junit5-extension-dmn/pom.xml
- test-utils/junit5-extension/pom.xml
Rename property `version.junit` to `version.junit4` since JUnit 5 becomes the leading JUnit version.
Introduce property `version.junit` with current version of JUnit 5.
This is a preparation step for migrating the test code basis.
> JUnit5 migration/JUnit bom

- freemarker-template-engine/pom.xml
- freemarker-template-engine/src/test/java/org/operaton/templateengines/engine/FreeMarkerScriptEngineTest.java
- internal-dependencies/pom.xml
- test-utils/junit5-extension-dmn/pom.xml
- test-utils/junit5-extension/pom.xml
Migrated with Open Rewrite recipe org.openrewrite.java.testing.junit5.JUnit5BestPractices.
Added required dependencies to internal-dependencies/pom.xml.
Use operaton-core-internal-dependencies BOM.
> Migrate to JUnit 5: freemarker-template-engine

- commons/logging/pom.xml
- commons/logging/src/test/java/org/operaton/commons/logging/BaseLoggerTest.java
- commons/logging/src/test/java/org/operaton/commons/logging/MdcAccessTest.java
- commons/pom.xml
- commons/typed-values/pom.xml
- commons/typed-values/src/test/java/org/operaton/bpm/engine/test/api/variable/PrimitiveValueTest.java
- commons/typed-values/src/test/java/org/operaton/bpm/engine/test/api/variable/VariableApiTest.java
- commons/typed-values/src/test/java/org/operaton/bpm/engine/test/variables/FileValueTypeImplTest.java
- commons/utils/pom.xml
- commons/utils/src/test/java/org/operaton/commons/utils/EnsureUtilTest.java
- commons/utils/src/test/java/org/operaton/commons/utils/IoUtilTest.java
- commons/utils/src/test/java/org/operaton/commons/utils/StringUtilTest.java
- commons/utils/src/test/java/org/operaton/commons/utils/cache/ConcurrentLruCacheTest.java
- internal-dependencies/pom.xml
- test-utils/junit5-extension-dmn/pom.xml
- test-utils/junit5-extension/pom.xml
Migrated with Open Rewrite recipe org.openrewrite.java.testing.junit5.JUnit5BestPractices.
Added required dependencies to internal-dependencies/pom.xml.
commons-testing stays with JUnit 4 since downstream testing classes use ProcessEngineLoggingRule.
> [#27] Migrate to JUnit 5: commons

- .github/workflows/build.yml
- use `junit-report-action` to publish test results and add a check to PR builds
- archive surefire reports
Fixes #67
> [#67] Publish and archive surefire reports

- .mvn/maven.config
- clients/java/client/pom.xml
- clients/java/client/src/it/java/org/operaton/bpm/client/client/ClientIT.java
- clients/java/client/src/it/java/org/operaton/bpm/client/rule/ClientRule.java
- clients/java/client/src/it/java/org/operaton/bpm/client/rule/EngineRule.java
- clients/java/client/src/it/java/org/operaton/bpm/client/task/ExternalTaskCustomExtensionPropertiesIT.java
- clients/java/client/src/it/java/org/operaton/bpm/client/task/ExternalTaskHandlerIT.java
- clients/java/client/src/it/java/org/operaton/bpm/client/topic/TopicSubscriptionIT.java
- clients/java/client/src/it/java/org/operaton/bpm/client/variable/FileSerializationIT.java
- clients/java/client/src/it/java/org/operaton/bpm/client/variable/JavaSerializationIT.java
- clients/java/client/src/it/java/org/operaton/bpm/client/variable/JsonSerializationIT.java
- clients/java/client/src/it/java/org/operaton/bpm/client/variable/JsonValueIT.java
- clients/java/client/src/it/java/org/operaton/bpm/client/variable/LocalVariableIT.java
- clients/java/client/src/it/java/org/operaton/bpm/client/variable/PrimitiveVariableIT.java
- clients/java/client/src/it/java/org/operaton/bpm/client/variable/XmlSerializationIT.java
- clients/java/client/src/it/java/org/operaton/bpm/client/variable/XmlValueIT.java
- clients/java/client/src/it/java/org/operaton/bpm/client/variable/pa/PaExceptionIT.java
- clients/java/client/src/it/java/org/operaton/bpm/client/variable/pa/PaSerializationIT.java
- clients/java/client/src/test/java/org/operaton/bpm/client/backoff/ExponentialBackoffStrategyTest.java
- clients/java/client/src/test/java/org/operaton/bpm/client/backoff/ExponentialErrorBackoffStrategyTest.java
- clients/java/client/src/test/java/org/operaton/bpm/client/impl/ExternalTaskClientBuilderImplTest.java
- clients/java/client/src/test/java/org/operaton/bpm/client/task/ExternalTaskImplTest.java
- clients/java/client/src/test/java/org/operaton/bpm/client/variable/DateValueMapperTest.java
- clients/java/pom.xml
This PR migrates the code from `clients` to JUnit 5.
The initial migration has been performed with Open Rewrite recipe `org.openrewrite.java.testing.junit5.JUnit5BestPractices`. Remaining gaps have been adopted manually.
> [#27] JUnit 5 migration: submodule clients

- .github/workflows/build.yml
> chore: Enable .m2 cache for GitHub pipelines

- .github/workflows/build.yml
The SonarQube analysis is incomplete when using shallow clone
> Prevent shallow clone in Git

- clients/java/client/src/test/java/org/operaton/bpm/client/variable/DateValueMapperTest.java
- commons/pom.xml
- connect/core/pom.xml
- connect/core/src/test/java/org/operaton/connect/spi/ConnectorsTest.java
- connect/http-client/pom.xml
- connect/http-client/src/test/java/org/operaton/connect/httpclient/HttpConnectorSystemPropertiesTest.java
- connect/http-client/src/test/java/org/operaton/connect/httpclient/HttpConnectorTest.java
- connect/http-client/src/test/java/org/operaton/connect/httpclient/HttpRequestConfigTest.java
- connect/http-client/src/test/java/org/operaton/connect/httpclient/HttpRequestTest.java
- connect/http-client/src/test/java/org/operaton/connect/httpclient/HttpResponseTest.java
- connect/pom.xml
- connect/soap-http-client/pom.xml
- connect/soap-http-client/src/test/java/org/operaton/connect/soap/httpclient/SoapHttpConnectorSystemPropertiesTest.java
- connect/soap-http-client/src/test/java/org/operaton/connect/soap/httpclient/SoapHttpConnectorTest.java
- connect/soap-http-client/src/test/java/org/operaton/connect/soap/httpclient/SoapHttpRequestTest.java
- engine-dmn/engine/src/test/java/org/operaton/bpm/dmn/engine/test/asserts/DmnDecisionTableResultAssert.java
- engine-dmn/feel-juel/pom.xml
- engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/batch/BatchSetRemovalTimeTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/concurrency/AbstractCompetingTransactionsOptimisticLockingTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/concurrency/BuiltinExceptionCodeForeignKeyConstraintViolationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/dmn/feel/FeelEnableLegacyBehaviorConfigTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/errorcode/ExceptionBuiltinCodesTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/errorcode/conf/BuiltinExceptionCodeProviderDisabledWithCustomProviderTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/errorcode/conf/CustomErrorCodeProviderTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/errorcode/conf/ExceptionCodeDisabledTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/standalone/scripting/EnvScriptResolutionTest.java
- internal-dependencies/pom.xml
- parent/pom.xml
- test-utils/junit5-extension/pom.xml
Migrate org.operaton.connect submodules to JUnit 5.
Performed Open Rewrite rule org.openrewrite.java.testing.junit5.JUnit5BestPractices and manually completed the migration.
Upgrade assertj to 3.26.3.
> [#27] Migrate to JUnit 5: org.operaton.connect submodules

- engine-plugins/identity-ldap/src/main/java/org/operaton/bpm/identity/impl/ldap/LdapIdentityProviderSession.java
* thrown an error only if id is null, do nothing if an authorization is missing
https://github.com/camunda/camunda-bpm-platform/issues/4293
Backported commit f1c8c6065c from the camunda-bpm-platform repository.
Original author: yanavasileva <yanavasileva@users.noreply.github.com>
> fix(identity/ldap): adjust ldap error handling (#4536)

- .github/workflows/build.yml
- distro/wildfly/subsystem/pom.xml
- distro/wildfly26/subsystem/pom.xml
- engine-rest/engine-rest/pom.xml
- engine/pom.xml
- parent/pom.xml
- pom.xml
- qa/large-data-tests/pom.xml
- qa/performance-tests-engine/pom.xml
- qa/test-old-engine/pom.xml
- quarkus-extension/engine/pom.xml
- spin/core/pom.xml
- spin/dataformat-json-jackson/pom.xml
- spin/dataformat-xml-dom-jakarta/pom.xml
- spin/dataformat-xml-dom/pom.xml
- webapps/pom.xml
Adds configuration of the jacoco-maven-plugin
- plugin version management in root pom.xml
- plugin configuration in parent pom.xml
Configure `argLine` properties of `maven-surefire-configurations` to prepend jacoco args
> [#78] Perform code coverage with JaCoCo on test execution 

- test-utils/junit5-extension/src/main/java/org/operaton/bpm/engine/test/junit5/ProcessEngineExtension.java
- test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/ProcessEngineExtensionServiceInjectionTest.java
This extends ProcessEngineExtension to be able to inject engine services into fields of the test class. By doing this, tests can be cleaner and just declare a fields of engine services that the test is using.
Fixes #105
> [#105] Extend ProcessEngineExtension to enable injection of engine services

- engine/src/main/java/org/operaton/bpm/engine/impl/cfg/ConfigurationLogger.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
- engine/src/test/java/org/operaton/bpm/engine/impl/cfg/ProcessEngineConfigurationTest.java
- engine/src/test/resources/operaton.cfg.skipIsolationLevelCheckEnabled.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4516
Backported commit d479f3bc3e from the camunda-bpm-platform repository.
> feat(engine): check transaction isolation level on init (#4526)

- qa/test-old-engine/pom.xml
- quarkus-extension/README.md
- quarkus-extension/engine/deployment/src/test/resources/org/operaton/bpm/quarkus/engine/test/config/mixed-application.properties
- quarkus-extension/engine/deployment/src/test/resources/org/operaton/bpm/quarkus/engine/test/config/process-engine-config-application.properties
* remove telemetry configuration property from `quarkus-extension` as it no longer exist
* exclude telemetry test in `old-engine` setup as telemetry feature is removed in newer versions; during rolling update users run old engine and data with new schema, so the test is not relevant for the scenario
https://github.com/camunda/camunda-bpm-platform/issues/4483
Backported commit abf8f55857 from the camunda-bpm-platform repository.
Original author: yanavasileva <yanavasileva@users.noreply.github.com>
> remove(tests): remove telemetry configuration property  (#4544)

- webapps/frontend/public/app/cockpit/locales/de.json
- webapps/frontend/public/app/cockpit/locales/en.json
related to #4315
Backported commit e0b2c191e6 from the camunda-bpm-platform repository.
Original author: Gergely Juhasz <gergely.juhasz@camunda.com>
> feat(cockpit): add rootInstanceId filter to humanTask search (#4509)

- engine-rest/engine-rest-openapi/src/main/templates/models/org/operaton/bpm/engine/rest/dto/MultiFormDeploymentDto.ftl
Related to https://github.com/camunda/camunda-bpm-platform/issues/4312
Backported commit 8789a9b748 from the camunda-bpm-platform repository.
> fix(openapi): make description for POST /deployment/create more clear

- engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/fetchAndLock/post.ftl
Related to https://github.com/camunda/camunda-bpm-platform/issues/4608
Backported commit 16f5002bdf from the camunda-bpm-platform repository.
> chore(docs): Fix sortOrder case in fetch and lock rest api example

- .mvn/maven.config
- engine/src/main/java/org/operaton/bpm/engine/impl/test/ProcessEngineAssert.java
- examples/invoice/src/test/java/org/operaton/bpm/example/invoice/InvoiceTestCase.java
- examples/pom.xml
Migrate the examples module to JUnit 5.
The code uses now ProcessEngineAssert, but this class dependet on JUnit 4's AssertionFailedError. This caused this error:
```
java.lang.NoClassDefFoundError: junit/framework/AssertionFailedError
at org.operaton.bpm.example.invoice.InvoiceTestCase.testHappyPathV1(InvoiceTestCase.java:91)
```
To avoid this JU4 dependency replaced by its supertype java.lang.AssertionError. The ProcessEngineAssert will be used also in other migrated test cases.
Removed "installAtEnd" from maven.config. Sometimes I need to have some modules like installed, and a full build takes long and may fail.
> (chore)JUnit5 migration: example submodule (#27)

- distro/tomcat/assembly/assembly.xml
Context: This fix adds juel to distro/lib folder.
Fixes: NoClassDefFound errors that users who copy distro/lib dependencies experience when starting with a Manual Installation of Tomcat 10
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4573
Backported commit 2fa8c6324c from the camunda-bpm-platform repository.
> chore(distro/tomcat/assembly): Add Juel to distro/lib Folder

- test-utils/junit5-extension/src/main/java/org/operaton/bpm/engine/test/junit5/ProcessEngineExtension.java
- test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/ProcessEngineExtensionSubTypeInjectionTest.java
This is to allow a class hierarchy where the base class is annotated with @ExtendWith(ProcessEngineExtension.class) and declares (protected/package private) fields for engine services.
Example for this need: `org.operaton.spin.plugin.variables.JsonSerializationWithValidationTest`
This test derives from `JsonSerializationTest` and the subclass would need the services injected into the fields of `JsonSerializationTest`.
> feat(tests): Enable ProcessEngineExtension to inject services into the super class of a test case (#27)

- parent/pom.xml
related to camunda/camunda-bpm-platform#4622
Backported commit 79ff55d871 from the camunda-bpm-platform repository.
> chore(deps): bump Tomcat to 10.1.29 (#4623)

- engine-rest/engine-rest-openapi/src/main/templates/models/org/operaton/bpm/engine/rest/dto/ModificationDto.ftl
- engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/ModificationDto.java
- engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/impl/ModificationRestServiceImpl.java
- engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/ModificationRestServiceInteractionTest.java
- engine/src/main/java/org/operaton/bpm/engine/impl/ModificationBuilderImpl.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmd/AbstractModificationCmd.java
- engine/src/main/java/org/operaton/bpm/engine/runtime/ModificationBuilder.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ModificationExecutionAsyncTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ModificationExecutionSyncTest.java
- engine/src/test/resources/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.syncAfterOneTaskProcess.bpmn20.xml
related to: #4620
Backported commit 1b9de30e4c from the camunda-bpm-platform repository.
Original author: Gergely Juhasz <gergely.juhasz@camunda.com>
> feat(engine): add historicProcInsQuery to executeModificationAsync

- distro/run/assembly/resources/default.yml
- distro/run/assembly/resources/production.yml
- distro/run/core/src/main/java/org/operaton/bpm/run/OperatonBpmRunRestConfiguration.java
- distro/run/core/src/main/java/org/operaton/bpm/run/property/OperatonBpmRunProperties.java
- distro/run/core/src/main/java/org/operaton/bpm/run/property/OperatonBpmRunRestProperties.java
- distro/run/core/src/test/java/org/operaton/bpm/run/test/config/rest/WadlDisabledTest.java
- distro/run/core/src/test/java/org/operaton/bpm/run/test/config/rest/WadlEnabledTest.java
- distro/run/core/src/test/java/org/operaton/bpm/run/test/config/rest/WadlUnsetTest.java
Context: Camunda-Run and Configuration of the WADL REST Endpoint
What: A new property is added that controls the WADL file, exposed via the REST API
Where: `camunda-run`
Endpoint: `/engine-rest/wadl.application`
Property: `camunda.bpm.run.rest.disable-wadl`
Values
- `true` disables the endpoint
- `false` enables the endpoint
- absence of the property has the same effect as the value `false` (endpoint is enabled)
Note: `production.yml` has the feature disabled by default
Co-authored-by: Petros Savvidis <petros.savvidis@camunda.com>
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4508
Backported commit 56673650f7 from the camunda-bpm-platform repository.
Original author: Jonathan Lukas <jonathan.lukas@camunda.com>
> chore(distro/run): Add Config for Disabling WADL

- engine-rest/engine-rest-openapi/src/main/templates/lib/commons/task-query-params.ftl
- engine-rest/engine-rest-openapi/src/main/templates/models/org/operaton/bpm/engine/rest/dto/runtime/task/TaskQueryDto.ftl
- engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/task/TaskQueryDto.java
- engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/TaskRestServiceQueryTest.java
- engine/src/main/java/org/operaton/bpm/engine/impl/TaskQueryImpl.java
- engine/src/main/java/org/operaton/bpm/engine/impl/json/JsonTaskQueryConverter.java
- engine/src/main/java/org/operaton/bpm/engine/task/TaskQuery.java
- engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/Task.xml
- engine/src/test/java/org/operaton/bpm/engine/test/api/filter/FilterTaskQueryTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskQueryTest.java
- adds functionality to filter tasks on a candidate group using a like-statement
related to #4540
Backported commit 79b001b337 from the camunda-bpm-platform repository.
Original author: Jordy Cantaert <jordy.cantaert@vaph.be>
> feat(engine): like-queries for candidate groups

- internal-dependencies/pom.xml
- parent/pom.xml
- quarkus-extension/pom.xml
- spring-boot-starter/pom.xml
- test-utils/assert/pom.xml
JUnit 5 dependencies after this change:
**Testing Instructions**
Execute
```
./mvnw dependency:list | grep org.junit | sort -u
```
Ensure that all tests have run.
Fixes #155
> chore(deps-dev): Ensure that everywhere the same JUnit 5 version is used (#155)

- distro/run/assembly/resources/default.yml
- distro/run/assembly/resources/production.yml
- distro/run/core/src/main/java/org/operaton/bpm/run/OperatonBpmRunConfiguration.java
- distro/run/core/src/main/java/org/operaton/bpm/run/OperatonBpmRunDeploymentConfiguration.java
- distro/run/core/src/main/java/org/operaton/bpm/run/OperatonBpmRunProcessEngineConfiguration.java
- distro/run/core/src/main/java/org/operaton/bpm/run/property/OperatonBpmRunDeploymentProperties.java
- distro/run/core/src/main/java/org/operaton/bpm/run/property/OperatonBpmRunProperties.java
- distro/run/core/src/test/java/org/operaton/bpm/run/test/config/deploy/DeployChangedOnlyDisabledTest.java
- distro/run/core/src/test/java/org/operaton/bpm/run/test/config/deploy/DeployChangedOnlyEnabledTest.java
- distro/run/core/src/test/java/org/operaton/bpm/run/test/config/deploy/DeployChangedOnlyUnsetTest.java
Description: The feature allows camunda-run to parameterise the filtering of duplicate resources via a configurable flag.
Feature-flag: This commit introduces the new feature flag `camunda.bpm.run.deployment.deploy-changed-only`
Default-value: `true` (to be backwards compatible with the previously hardcoded behaviour)
Has-refactoring: This commit also refactors the `@CamundaBpmRunConfiguration` and all its dependencies to be simpler and conforming to spring-boot best practices.
Has-unit-tests: This commit adds three test cases for covering the enabling | Disabling | Absence of the new property.
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/2652
Backported commit e7941a3f50 from the camunda-bpm-platform repository. Original author: psavidis …
> feat(distro/run): Make deployChangedOnly Configurable

- engine-rest/engine-rest-openapi/src/main/templates/paths/metrics/get.ftl
related to https://github.com/camunda/camunda-bpm-platform/issues/4554
Backported commit b1c8dd36919 from the camunda-bpm-platform repository. Original author: Timo Kramer <4785848+TimoKramer@users.noreply.github.com>"
> fix(openapi): fix incorrect schema for metrics param (#4555)

- engine/src/test/java/org/operaton/bpm/engine/test/history/JobEntityAndJobLogBatchIdTest.java
Related to https://github.com/camunda/camunda-bpm-platform/issues/4206
Backported commit ff4229c448 from the camunda-bpm-platform repository.
> fix(engine): Add missing HistoryLevel annotation to test

- engine-rest/engine-rest-jakarta/pom.xml
- engine-spring/core/pom.xml
- engine-spring/pom.xml
- engine/pom.xml
- qa/pom.xml
- quarkus-extension/pom.xml
- spin/core/pom.xml
- spin/dataformat-json-jackson/pom.xml
- spin/dataformat-xml-dom-jakarta/pom.xml
- spin/dataformat-xml-dom/pom.xml
- spin/pom.xml
- webapps/assembly-jakarta/pom.xml
Merged profiles related to Java versions because minimal supported Java version is now 17 and all profiles either targeted versions below or from Java 17.
Fixes #169
> chore(build): Remove Java related profiles (#169)

- engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricBatchRestServiceInteractionTest.java
- engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricDecisionInstanceRestServiceInteractionTest.java
- engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricProcessInstanceRestServiceInteractionTest.java
- engine/src/main/java/org/operaton/bpm/engine/impl/util/EnsureUtil.java
- internal-dependencies/pom.xml
- test-utils/assert/core/src/test/java/org/operaton/bpm/engine/test/assertions/bpmn/ProcessInstanceAssertIsWaitingForJoinTest.java
Reduce build warnings.
Resolved:
```
[WARNING] Some problems were encountered while building the effective model for org.operaton.bpm:operaton-core-internal-dependencies:pom:1.0.0-beta-2
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.junit.jupiter:junit-jupiter-api:jar -> duplicate declaration of version ${version.junit5} @ line 117, column 19
```
Adds overloaded methods to `EnsureUtil` that take a `String...` parameter and call the method with `Object...` parameter. By doing so cases where ensureXXX methods are called with string args the new methods will be taken. This reduces some warnings with message:
```non-varargs call of varargs method with inexact argument type for last parameter```
There are still some in tests …
> chore(build): Reduce build warnings (#176)

- spin/core/pom.xml
- spin/dataformat-json-jackson/pom.xml
- spin/dataformat-xml-dom/pom.xml
This change removes the profile from all related pom.xml files.
**Testing Instruction**
Execute: 
```
mvn help:all-profiles | grep 'Active' | awk '{print $3}' | sort -u
```
This should not list the profile anymore.
> chore(build): remove profile 'disable-javascript-tests' (#181)

- engine-rest/docs/pom.xml
original commit message: reintroduce oracle jdk stages (#4610)
related to https://github.com/camunda/team-automation-platform/issues/52
Backported commit 47c0504b58 from the camunda-bpm-platform repository.
> chore(ci): make frontend build skippable

- distro/run/pom.xml
This configuration of `maven-enforcer-plugin` is obsolete, since minimal Java version is now 17.
> chore(build): remove obsolete enforcer configuration

- distro/wildfly/subsystem/pom.xml
- distro/wildfly26/subsystem/pom.xml
- engine-rest/engine-rest/pom.xml
- engine/pom.xml
- parent/pom.xml
- qa/large-data-tests/pom.xml
- qa/performance-tests-engine/pom.xml
- qa/test-old-engine/pom.xml
- quarkus-extension/engine/pom.xml
- spin/core/pom.xml
- spin/dataformat-json-jackson/pom.xml
- spin/dataformat-xml-dom-jakarta/pom.xml
- spin/dataformat-xml-dom/pom.xml
- webapps/pom.xml
This change makes the JVM arguments used by surefire more flexible.
In `parent/pom.xml` a property `surefire.argLine` is defined. This property is now used in any places that require additional customization of the JVM args.
Often customization is required for adjusting memory settings. The memory settings are now defined with a default value in the property `surefire.memArgs` in the parent POM. 
Modules that need customization of memory now just override the `surefire.memArgs` instead of overriding surefire's `argLine` property. This way we make sure that the surefire default arg line is always taken.
The original intent was to get rid off the warning:
```OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended``` …
> chore(build): Define property 'surefire.argLine' (#176)

- internal-dependencies/pom.xml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4720
Backported commit 57d462377d3 from the camunda-bpm-platform repository.
> chore(internal-dependencies): Bump to commons-io:2.17.0

- engine-plugins/identity-ldap/pom.xml
- engine-rest/pom.xml
- engine/pom.xml
- parent/pom.xml
- spring-boot-starter/pom.xml
- webapps/pom.xml
Defines a property `surefire.forkCount` on `parent/pom.xml` with value `0.5C`, and configure surefire's `forkCount` with this value.
Override the property with value `1` on modules that can't execute multiple tests in parallel, because they need exclusive resource access (e.g. port or directory).
fixes #205
> feat(ci): Improve build performance by configure surefire forkCount (#205)

- engine/src/main/java/org/operaton/bpm/engine/ProcessEngineProvider.java
- engine/src/main/java/org/operaton/bpm/engine/test/ProcessEngineRule.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/history/BatchHistoricDecisionInstanceDeletionTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/BatchHelper.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/BatchModificationHelper.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/BatchRestartHelper.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/BatchSuspensionHelper.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/batch/BatchMigrationHelper.java
- engine/src/test/java/org/operaton/bpm/engine/test/util/PluggableProcessEngineTest.java
- qa/large-data-tests/src/test/java/org/operaton/bpm/qa/largedata/util/BatchModificationJobHelper.java
This change introduces the interface `ProcessEngineProvider`, which is implemented by the classes `ProcessEngineRule` and `PluggableProcessEngineTest`.
The BatchHelper class hierarchy is decoupled from `ProcessEngineRule` and `PluggableProcessEngineTest` by using this interface to access the ProcessEngine and its services.
This is a preparation step for migrating test cases away from these both classes.
related to #27
> refactor(tests): Make BatchHelper independent of ProcessEngineRule

- pom.xml
This change adds a profile `openrewrite` to the root POM and activates the "Remove unused imports" recipe.
The changes by the recipe are added via https://github.com/operaton/operaton/pull/221
See also this [forum thread](https://forum.operaton.org/t/open-rewrite-cleanups/72).
fixes #220
> chore: Add Open Rewrite plugin

- engine/src/main/java/org/operaton/bpm/engine/test/ProcessEngineRule.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/BatchModificationHelper.java
- engine/src/test/java/org/operaton/bpm/engine/test/util/PluggableProcessEngineTest.java
- internal-dependencies/pom.xml
- qa/large-data-tests/pom.xml
- qa/large-data-tests/src/test/java/org/operaton/bpm/qa/largedata/DeleteDeploymentCascadeTest.java
- qa/large-data-tests/src/test/java/org/operaton/bpm/qa/largedata/SetJobRetriesAsyncTest.java
- qa/large-data-tests/src/test/java/org/operaton/bpm/qa/largedata/optimize/OptimizeApiPageSizeTest.java
This change refactors the code for module `qa/large-data-tests`.
It builds up on the refactoring of `BatchHelper` (https://github.com/operaton/operaton/pull/217).
related to #27 
fixes #225
> refactor(tests): JUnit 5 migration - module qa/large-data-tests

- .github/workflows/build.yml
Avoids that the `build` job us triggered on changes to documentation, other workflows and some specific file.
Also changes to `distros` will not trigger the main build. This should be done later in a workflow that builds distros.
Also: remove matrix build; will be added with scheduled build
fixes #241
> feat(ci): Define paths-ignore for files that should not trigger a build

- engine-rest/engine-rest-openapi/src/main/templates/models/org/operaton/bpm/engine/rest/dto/history/HistoricTaskInstanceDto.ftl
- engine-rest/engine-rest-openapi/src/main/templates/models/org/operaton/bpm/engine/rest/dto/runtime/task/TaskDto.ftl
Related to https://github.com/camunda/camunda-bpm-platform/issues/4683
Backported commit d27a7be1a70 from the camunda-bpm-platform repository.
> openapi(tasks): include task state in response specification

- juel/pom.xml
Resolves a NoClassDefFoundError for JakartaEL classes at test runtime for modules transitvely depending on juel.
fixes #242
> fix(build,juel): Use managed version of jakarta-el and use compile scope for juel

- clients/java/client/pom.xml
Tests disabled to avoid flaky builds.
relates to #251
> Disable failsafe in external task client

- engine/src/main/java/org/operaton/bpm/engine/impl/batch/variables/BatchSetVariablesHandler.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmd/AbstractVariableCmd.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmd/SetExecutionVariablesCmd.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/RuntimeServiceTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/SetVariablesBatchTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/history/JobEntityAndJobLogBatchIdTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/util/ExecutableProcessUtil.java
Related to https://github.com/camunda/camunda-bpm-platform/issues/4795
Backported commit 4b101ea9cbe from the camunda-bpm-platform repository.
> feat(engine): don't fail on change variables async when process instance does not exist

- .github/workflows/nighly-build.yml
- pom.xml
- provide `nightly-build.yml`:
- build with goals `clean install`
- use local uncached repository
- archive reports
- archive distros
- Remove matrix build from main build pipeline
- Reports
- dependency analysis
- dependency updates
- plugin updates
- sloc
relates to https://github.com/operaton/operaton/issues/201
> Set up nightly build

- parent/pom.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4751
Backported commit 119cbf8804b from the camunda-bpm-platform repository.
Original author: Miklas Boskamp <20189772+mboskamp@users.noreply.github.com>
> chore(parent): Bump Spring Libraries

- bom/operaton-bom/pom.xml
- bom/operaton-only-bom/pom.xml
- bom/pom.xml
- distro/run/assembly/pom.xml
- distro/run/core/pom.xml
- distro/run/distro/pom.xml
- distro/run/modules/oauth2/pom.xml
- distro/run/modules/pom.xml
- distro/run/modules/rest/pom.xml
- distro/run/modules/webapps/pom.xml
- distro/run/qa/example-plugin/pom.xml
- distro/run/qa/integration-tests/pom.xml
- distro/run/qa/pom.xml
- distro/run/qa/runtime/pom.xml
- engine-rest/assembly/pom.xml
- engine-rest/engine-rest-jakarta/pom.xml
- engine-rest/engine-rest-openapi-generator/pom.xml
- engine-rest/engine-rest-openapi/pom.xml
- engine-rest/engine-rest/pom.xml
- examples/invoice-jakarta/pom.xml
- examples/invoice/pom.xml
- parent/pom.xml
- qa/integration-tests-webapps/integration-tests/pom.xml
- qa/integration-tests-webapps/shared-engine/pom.xml
- test-utils/assert/core/pom.xml
- test-utils/assert/qa/pom.xml
- webapps/assembly-jakarta/pom.xml
- webapps/assembly/pom.xml
The <relativePath> tag is not needed when the pom is located in the parent directory.
fixes #301
> chore(build): Remove obsolete relativePath declarations

- .github/scripts/prepare-distros-archive.sh
- .github/workflows/build.yml
- .github/workflows/nighly-build.yml
- distro/wildfly/subsystem/pom.xml
- distro/wildfly26/subsystem/pom.xml
- parent/pom.xml
- pom.xml
This change makes the distributions "Operaton (Tomcat Bundle)" and "Operaton SQL Scripts" available as separately downloadable artifacts. Before, both distros were packaged into a single "distros" zip file.
fixes #280
> Make distros downloadable as separate artifacts

- clients/java/pom.xml
- commons/typed-values/pom.xml
- distro/jboss/pom.xml
- distro/license-book/pom.xml
- engine-cdi/core/pom.xml
- engine-cdi/jakarta/pom.xml
- engine-dmn/pom.xml
- engine-spring/core-6/pom.xml
- engine-spring/core/pom.xml
- javaee/ejb-service/pom.xml
- juel/pom.xml
- model-api/pom.xml
- quarkus-extension/pom.xml
- spring-boot-starter/pom.xml
- test-utils/archunit/pom.xml
- test-utils/assert/core/pom.xml
- test-utils/assert/qa/pom.xml
- test-utils/junit5-extension-dmn/pom.xml
fix(engine): Change parent poms from operaton-database-settings to root/parent pom's
- replace operaton-database-settings with root/parent pom's where database dependencies and settings are not required
fixes #294
> Changed parent poms from operaton-database-settings to root/parent pom's

- clients/java/client/src/it/java/org/operaton/bpm/client/client/ClientIT.java
- clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/AbstractTypedValueMapper.java
- clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/VariableValue.java
- clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/mapper/ByteArrayValueMapper.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java
- model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/util/GetBpmnModelElementTypeRule.java
- model-api/cmmn-model/src/test/java/org/operaton/bpm/model/cmmn/util/GetCmmnModelElementTypeRule.java
- model-api/xml-model/src/test/java/org/operaton/bpm/model/xml/instance/ModelElementInstanceTest.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/cdi/beans/ExampleSignallableActivityBehaviorBean.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/war/JavaDelegateResolutionTest.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/request/JobExecutorRequestContextLocalInvocationTest.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/event/beans/ExecutionListenerProcessApplication.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/message/IntermediateMessageCatchEventTest.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/AsyncIntermediateThrowSignalEventTest.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/FailingJobBoundaryTimerWithDelegateVariablesTest.java
- qa/large-data-tests/src/test/java/org/operaton/bpm/qa/largedata/util/EngineDataGenerator.java
- spring-boot-starter/starter-qa/integration-test-webapp/invoice-example/src/main/java/org/operaton/bpm/qa/Application.java
- spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/OAuth2IdentityProvider.java
- test-utils/assert/core/src/main/java/org/operaton/bpm/engine/test/assertions/bpmn/AbstractAssertions.java
- test-utils/assert/core/src/main/java/org/operaton/bpm/engine/test/assertions/bpmn/BpmnAwareTests.java
- test-utils/assert/core/src/main/java/org/operaton/bpm/engine/test/assertions/cmmn/AbstractCaseAssert.java
- rename variables that hide fields
- remove obsolete public modifier
- refactor lamdas in assertThatThrownBy() to have only one invocation throwing a runtime exception
- replace isAfterOrEqualsTo by isAfterOrEqualTo
- replace isBeforeOrEqualsTo by isBeforeOrEqualTo
- add missing `@Override` annotations
- Remove unnecessary public modifiers from tests
- Use replace() instead of replaceAll() where no regexp replacement is needed
- refactor string concatenation
- remove obsolete throws declaration
> chore: Code cleanup, resolve Sonar issues

- connect/pom.xml
- database/pom.xml
- engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.db2.create.engine.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.h2.create.engine.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.mariadb.create.engine.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.mssql.create.engine.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.mysql.create.engine.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.oracle.create.engine.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.postgres.create.engine.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/liquibase/operaton-changelog.xml
- engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/db2_engine_7.22_to_7.23.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/h2_engine_7.22_to_7.23.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/mariadb_engine_7.22_to_7.23.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/mssql_engine_7.22_to_7.23.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/mysql_engine_7.22_to_7.23.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/oracle_engine_7.22_to_7.23.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/postgres_engine_7.22_to_7.23.sql
- qa/test-db-instance-migration/pom.xml
- qa/test-db-instance-migration/test-fixture-723/pom.xml
- qa/test-db-instance-migration/test-fixture-723/src/main/java/org/operaton/bpm/qa/upgrade/TestFixture.java
- qa/test-db-instance-migration/test-fixture-723/src/main/resources/operaton.cfg.xml
- qa/test-db-rolling-update/create-new-engine/pom.xml
- qa/test-db-rolling-update/create-old-engine/pom.xml
- qa/test-db-rolling-update/create-old-engine/src/main/resources/operaton.auth.cfg.xml
- qa/test-db-rolling-update/rolling-update-util/pom.xml
- qa/test-db-rolling-update/test-old-engine/pom.xml
- qa/test-old-engine/pom.xml
- spin/pom.xml
* Add instance migration project
* Adjust create scripts
* Create upgrade scripts
* Add the new changeSets to liquibase
* add migration fixture for 7.23
* update old engine test
* remove telemetry fields from old engine cfg
* chore(database): remove telemetryReporterActivate from old-engine and rolling-update tests
* adjust old version for spin and connect
* exclude DatabaseNamingConsistencyTest in test-old-engine
* chore(database): activate oracle23 in old-engine stage in CI (#4677)
related to #203
related to camunda/camunda-bpm-platform#4556
Backported commit 396d635ce7 from the camunda-bpm-platform repository.
> chore(version): Update database version

- engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/event/AbstractCdiEventListener.java
- engine-spring/core/src/main/java/org/operaton/bpm/engine/spring/components/scope/ProcessScope.java
- engine/src/main/java/org/operaton/bpm/engine/impl/context/Context.java
- marked `Context#getExecutionContext` for removal
- replaced usages by `getBpmnExecutionContext`
> chore: Resolve deprecation `Context#getExecutionContext`

- distro/run/qa/integration-tests/pom.xml
- distro/run/qa/runtime/pom.xml
- pom.xml
- qa/integration-tests-engine-jakarta/pom.xml
- qa/integration-tests-engine/pom.xml
- qa/integration-tests-webapps/shared-engine/pom.xml
- qa/large-data-tests/pom.xml
- quarkus-extension/engine/qa/pom.xml
- spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-all/pom.xml
- spring-boot-starter/starter-qa/integration-test-webapp/runtime/pom.xml
- test-utils/assert/qa/pom.xml
Property `install.skip` is added to the root POM with value `false`, and used to configure the `skip` property for the maven-install-plugin.
All modules that require skipping the install plugin because they do not produce a 'main' jar override the property value. This makes the definition of the maven-install-plugin in these POMs obsolete and therefore the files smaller.
Additionally skipping install for distro/run qa modules.
fixes #342
> refactor(build): Introduce `install.skip` property

- pom.xml
Report does not contain unwanted plugin version updates:
closes #352
> chore(build): Ignore alpha/beta/4.0.0 versions in plugin-updates report

- .github/jreleaser/changelog.tpl
- .github/scripts/jacoco-create-flag-files.sh
- .github/scripts/prepare-reports.sh
- .github/workflows/build.yml
- .github/workflows/nighly-build.yml
- .github/workflows/release.yml
- jreleaser.yml
This change makes the Nightly Build workflow use JReleaser to produce a preliminary release. The Nightly Build is now more aligned to the Release workflow.
For manual runs, the Nightly Build allows to specify the Java versions to build against.
Project Reports are attached as zip file to the release artifacts.
jreleaser.yml:
- include 'run' distro as artifacts
- package project reports as zip and attach as release artifacts
- set previousTagName: 1.0.0-beta-2
nightly-build.yml:
- use jacoco-create-flag-files.sh
- add `release` job
- include 'distro-run'
release.yml:
- set JRELEASER_PRERELEASE_ENABLED: false
- include 'distro-run'
prepare-reports.sh:
- package reports as zip
jacoco-create-flag-files.sh:
- extract shell script from nightly-build.yml
build.yml:
- use …
> chore(build): Use JReleaser for nightly releases

- engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/DeploymentRestServiceInteractionTest.java
- engine-spring/core/src/test/java/org/operaton/bpm/engine/spring/test/components/ProcessStartingBeanPostProcessorTest.java
- engine-spring/core/src/test/java/org/operaton/bpm/engine/spring/test/components/scope/ScopingTest.java
- engine-spring/core/src/test/java/org/operaton/bpm/engine/spring/test/plugin/SpringProcessEnginePluginTest.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/local/LocalSFSBInvocationTest.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/local/LocalSLSBInvocationTest.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/local/LocalSingletonBeanInvocationTest.java
- test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/ProcessEngineExtensionRequiredHistoryLevelAuditTest.java
Assertions such as org.junit.Assert.assertEquals expect the first argument to be the expected value and the second argument to be the actual value
Performed cleanup with Open Rewrite recipe org.openrewrite.java.testing.cleanup.AssertionsArgumentOrder
related to #88
> refactor: Use correct order for assertions

- .github/workflows/nighly-build.yml
- distro/run/assembly/assembly.xml
- distro/tomcat/assembly/assembly.xml
- distro/wildfly/assembly/assembly.xml
- engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/DeploymentRestServiceInteractionTest.java
- engine-spring/core/src/test/java/org/operaton/bpm/engine/spring/test/components/ProcessStartingBeanPostProcessorTest.java
- engine-spring/core/src/test/java/org/operaton/bpm/engine/spring/test/components/scope/ScopingTest.java
- engine-spring/core/src/test/java/org/operaton/bpm/engine/spring/test/plugin/SpringProcessEnginePluginTest.java
- jreleaser.yml
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/local/LocalSFSBInvocationTest.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/local/LocalSLSBInvocationTest.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/local/LocalSingletonBeanInvocationTest.java
- test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/ProcessEngineExtensionRequiredHistoryLevelAuditTest.java
Extend nightly & release build to publish distributions to Homebrew.
- Extend `jreleaser.yml`
Exended "Nightly Build" workflow
- Allow skipping of tests for manual execution
- Make Java 17 only as default
related to #358
> Add Homebrew distribution

- engine/src/main/java/org/operaton/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
- engine/src/main/java/org/operaton/bpm/engine/impl/scripting/engine/OperatonScriptEngineManager.java
- parent/pom.xml
Notes
- Bumps icu:icu4j to version 71.1
Introduces:
OperatonScriptEngineManager - Class that allows to parameterise behaviour needed for a given JS engine: a) After the engines are detected from the classpath b) Before the engines are created
GraalVM Warnings
The commit sets the System property to disable the respective warnings introduced by bumping GraalVM to version 21.3.10.
- The system property is always set when a GraalJS script engine is found on the classpath
- The above applies by default to all distros
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4299
Backported commit 14a704b522 from the camunda-bpm-platform repository.
> chore(engine,parent): Bump GraalVM to 21.3.12

- engine/src/test/java/org/operaton/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupSchedulerCmdTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskConditionsTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/history/BatchHistoricDecisionInstanceDeletionTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/batch/BatchSetRemovalTimeTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/batch/BatchSetRemovalTimeUserOperationLogTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/BatchQueryTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/BatchStatisticsQueryTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceAsyncOperationsTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/CorrelateAllMessageBatchTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ModificationExecutionAsyncTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/RestartProcessInstanceAsyncTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/SetVariablesBatchTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/UpdateProcessInstancesSuspendStateAsyncTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/VariableInstanceQueryTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationTransitionInstancesTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/batch/BatchMigrationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskLastUpdatedTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/logging/TestMdcFacade.java
- qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7190/job/SetJobRetriesWithDueDateTest.java
- spring-boot-starter/starter/src/test/java/org/operaton/bpm/spring/boot/starter/ProcessApplicationIT.java
This change resolves 3 deprecations:
- Replace `MockitoAnnotations.initMocks()` by `openMocks()`
- Replace `AbstractDateAssert#isEqualToIgnoringMillis` by `isCloseTo()`
- Replace `Java6Assertions.assertThat` by `Assertions.assertThat`
> Resolve deprecations: MockitoAnnotations & AbstractDateAssert

- database/pom.xml
- distro/sql-script/pom.xml
- distro/sql-script/src/test/java/org/operaton/bpm/sql/test/SqlScriptTest.java
Fix the test when `h2-in-memory` profile is enabled by adding property `database.type` in the profile in `database/pom.xml`.
Migrate SqlScriptTest to JUnit 5. Using `@EnabledIf` feature and check for the existence of files in target/test-classes/scripts-old, which is populated when the `check-sql` profile is active.
closes #376
related to #27
Execute 
```
./mvnw -f distro/sql-script -DskipTests=false -Ph2-in-memory
```
before and after change.
With the change the tests that need `scripts-old` are skipped.
> fix(tests): Fix SqlScriptTest

- commons/typed-values/src/test/java/org/operaton/bpm/engine/test/variables/FileValueTypeImplTest.java
- connect/http-client/src/test/java/org/operaton/connect/httpclient/HttpConnectorTest.java
- connect/http-client/src/test/java/org/operaton/connect/httpclient/HttpResponseTest.java
- engine-dmn/feel-juel/src/test/java/org/operaton/bpm/dmn/feel/impl/FeelExceptionTest.java
- engine-plugins/connect-plugin/src/test/java/org/operaton/connect/plugin/ConnectProcessEnginePluginTest.java
- engine-plugins/spin-plugin/src/test/java/org/operaton/spin/plugin/variables/JsonSerializationTest.java
- engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/standalone/HalResourceCacheTest.java
- engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/util/NoIntermediaryInvocationTest.java
Refactor tests that check for exceptions to have only a single call in the calling code that could throw a RuntimeException.
Refactor to use `assertThatThrownBy()` for checking code for exceptions thrown.
Minor code cleanups: Removing unthrown exceptions, removed unused variable assignments etc.
related to #88, #27
> refactor(tests): Testing exceptions with only one possible invocation throwing

- engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/ProcessVariables.java
- engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/NamedProcessEngineServicesProducer.java
- engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/annotation/StartProcessInterceptor.java
- engine/src/main/java/org/operaton/bpm/container/impl/jmx/MBeanServiceContainer.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cfg/JakartaTransactionProcessEngineConfiguration.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cfg/JtaProcessEngineConfiguration.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmd/DeleteTaskCmd.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetDeploymentBpmnModelInstanceCmd.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetDeploymentProcessDiagramCmd.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetDeploymentProcessDiagramLayoutCmd.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetDeploymentProcessModelCmd.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetFormKeyCmd.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmd/SetJobDuedateCmd.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/cmd/GetDeploymentCaseDiagramCmd.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/handler/CallingTaskItemHandler.java
- engine/src/main/java/org/operaton/bpm/engine/impl/db/sql/DbSqlSession.java
- engine/src/main/java/org/operaton/bpm/engine/impl/util/StringUtil.java
- engine/src/test/java/org/operaton/bpm/application/impl/embedded/EmbeddedProcessApplicationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/repository/diagram/ProcessDiagramRetrievalTest.java
- javaee/jobexecutor-ra/src/main/java/org/operaton/bpm/container/impl/threading/ra/JcaExecutorServiceConnector.java
resolve Sonar findings of type [java:7158](https://sonarcloud.io/project/issues?rules=java%3AS7158&issueStatuses=OPEN%2CCONFIRMED&id=operaton_operaton)
- use StringUtils#hasText() when checking for non-null and not-empty
- use ObjectUtils#isEmpty() when checking for null or empty
- use String#isEmpty() when the checked string is guaranteed non-null and only empty/not-empty is checked
Deprecate `org.operaton.bpm.engine.impl.util.StringUtil#hasText(String)`
related to #88
closes #410
> refactor: Use StringUtils#hasText(), ObjectUtils#isEmpty, String#isEmpty

- engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/event/CdiEventSupportBpmnParseListener.java
- engine/src/main/java/org/operaton/bpm/application/impl/event/ProcessApplicationEventParseListener.java
- engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java
- engine/src/main/java/org/operaton/bpm/engine/impl/pvm/ProcessDefinitionBuilder.java
- engine/src/main/java/org/operaton/bpm/engine/impl/pvm/process/ScopeImpl.java
- engine/src/main/java/org/operaton/bpm/engine/impl/pvm/process/TransitionImpl.java
- engine/src/test/java/org/operaton/bpm/engine/test/standalone/entity/EntitySerializationTest.java
Methods in `TransitionImpl` & `ScopeImpl` regarding execution listeners have been deprecated. Documented in Javadoc their replacement, resolved usages of the deprecated methods and marked those methods for removal.
> chore(engine): Resolve & document deprecations in TransitionImpl, ScopeImpl

- engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/ProcessInstanceAuthorizationTest.java
Resolve: Testing exceptions with only one possible invocation throwing
Refactor tests that check for exceptions to have only a single call in the calling code that could throw a RuntimeException.
Refactor to use `assertThatThrownBy()` for checking code for exceptions thrown.
Using Copilot to refactor code. Using prompt:
"Use assertThatThrownBy
Preserve line comments
Place „// when“ above assertThatThrownBy
Place „// then“ before the first assertion
Remember that the failure message is the first assertion
Use hasMessageContaining as replacement for assertTextPresent
"
related to #88, #27
> refactor(tests): Refactor ProcessInstanceAuthorizationTest

- engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/TaskAuthorizationTest.java
Refactor tests that check for exceptions to have only a single call in the calling code that could throw a RuntimeException.
Refactor to use `assertThatThrownBy()`` for checking code for exceptions thrown.
Fix copy/paste error in testProcessTaskClaimTaskWithTaskWorkPermissionOnAnyTask
related to #88, #27
> refactor(tests): Replace try/catch by assertThatThrownBy

- commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/impl/VariableMapImpl.java
- engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/AbstractVariableMap.java
- engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/el/VariableContextScriptBindings.java
- engine-dmn/engine/src/test/java/org/operaton/bpm/dmn/engine/delegate/DmnDecisionEvaluationListenerTest.java
- engine-dmn/feel-scala/src/main/java/org/operaton/bpm/dmn/feel/impl/scala/function/builder/CustomFunctionBuilderImpl.java
- engine-plugins/identity-ldap/src/main/java/org/operaton/bpm/identity/impl/ldap/LdapIdentityProviderSession.java
- engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java
- engine/src/main/java/org/operaton/bpm/application/AbstractProcessApplication.java
- engine/src/main/java/org/operaton/bpm/container/impl/deployment/scanning/ClassPathProcessApplicationScanner.java
- engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ShellActivityBehavior.java
- engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java
- engine/src/main/java/org/operaton/bpm/engine/impl/calendar/CronExpression.java
- engine/src/main/java/org/operaton/bpm/engine/impl/history/SynchronousOperationLogProducer.java
- engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/AcquiredJobs.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/TaskEntity.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/TaskManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/plugin/AdministratorAuthorizationPlugin.java
- engine/src/main/java/org/operaton/bpm/engine/impl/scripting/engine/ScriptBindings.java
- engine/src/main/java/org/operaton/bpm/engine/impl/xml/ProblemImpl.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceQueryTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/bpmn/scripttask/ScriptTaskTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/bpmn/tasklistener/TaskListenerEventLifecycleTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/cmmn/handler/CaseHandlerTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorBatchTest.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/jobexecution/ClassloadingDuringJobExecutionTest.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/scriptengine/GroovyAsyncScriptExecutionTest.java
- qa/large-data-tests/src/test/java/org/operaton/bpm/qa/largedata/util/EngineDataGenerator.java
- spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/format/TypeHelper.java
- spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/actuator/JobExecutorHealthIndicator.java
- Join AssertJ assertions to chain 
- remove unnecessary try/finally
- Avoid wildcards extending final types 
- Use isEmpty() to check whether a collection is empty 
- Use text blocks 
- Rename fields not to match enclosing class name
- Static import of ConditionQueryParameterDto constants
- Remove unnecessary boxing
- Remove unnecessary parantheses for lambda parameters
- Use isEmpty() to check whether a string is empty or not
related to #88 #85
> refactor: Resolve Sonar warnings

- .github/workflows/nighly-build.yml
- make sure that the right version without "-SNAPSHOT" is passed as payload to the docker build workflow
- skip trigger docker build when performing dry run
related to operaton/operaton-docker#2
> build: Fix docker trigger

- distro/wildfly/modules/pom.xml
- distro/wildfly/modules/src/main/modules/org/operaton/bpm/operaton-engine/main/module.xml
- distro/wildfly/modules/src/main/modules/org/springframework/spring-core/main/module.xml
- distro/wildfly/modules/src/main/modules/org/springframework/spring-jcl/main/module.xml
The Wildfly distribution was missing dependencies on Spring Core. Spring Core itself has a dependency on Spring JCL.
This changes adds the Wildfly modules for spring-core and spring-jcl.
closes #419
> fix(wildfly): Add missing modules for Spring dependencies

- engine/src/test/java/org/operaton/bpm/engine/test/api/identity/AuthorizationQueryTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/identity/AuthorizationServiceAuthorizationsTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ActivityStatisticsQueryTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/BatchQueryTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/queries/BoundedNumberOfMaxResultsTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/CaseExecutionQueryTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/CaseInstanceQueryTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/CreateAndResolveIncidentTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/batch/BatchMigrationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/bpmn/async/AsyncAfterTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/bpmn/callactivity/CallActivityDelegateMappingTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/bpmn/callactivity/CallActivityTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/bpmn/callactivity/CaseCallActivityTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/compensate/CompensationEventParseInvalidProcessTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/conditional/BoundaryConditionalEventTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/error/BoundaryErrorEventTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/cmmn/casetask/CaseTaskTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/cmmn/cmmn10/Cmmn10CompatibilityTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/cmmn/deployment/CmmnDeployerTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/AcquirableJobCacheTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/standalone/interceptor/CommandContextInterceptorTest.java
Resolves Sonar issues of type java:S5778 Only one method invocation is expected when testing runtime exceptions
related to #88
> refactor: Extract method calls in try-blocks within tests to variables

- commons/testing/src/main/java/org/operaton/commons/testing/ProcessEngineLoggingRule.java
- spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/AbstractSpringSecurityIT.java
- spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OperatonBpmSampleApplicationIT.java
- spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OperatonBpmSecurityAutoConfigOauth2ApplicationIT.java
- spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/OAuth2GrantedAuthoritiesMapperIT.java
- spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/OperatonIdentityProviderIT.java
- Convert tests in "operaton-bpm-spring-boot-starter-security" to JUnit5
- Create ProcessEngineLoggingExtensions as JUnit5 replacement for ProcessEngineLoggingRule
realtes to: #27
> chore: Convert tests to JUnit 5.

- clients/java/client/src/main/java/org/operaton/bpm/client/impl/EngineClient.java
- engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/CustomJacksonDateFormatTest.java
- engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/FilterRestServiceInteractionTest.java
- engine/src/main/java/org/operaton/bpm/engine/impl/calendar/DurationHelper.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/GroupAuthorizationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/StandaloneTaskGetVariableAuthorizationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/HandleTaskAuthorizationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/getvariable/ProcessTaskAuthorizationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/getvariable/ProcessTaskReadPermissionAuthorizationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/getvariable/ProcessTaskReadVariablePermissionAuthorizationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/getvariable/StandaloneTaskAuthorizationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/getvariable/StandaloneTaskReadPermissionAuthorizationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/getvariable/StandaloneTaskReadVariablePermissionAuthorizationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/updatevariable/ProcessTaskAuthorizationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/updatevariable/StandaloneTaskAuthorizationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/identity/AuthorizationServiceAuthorizationsTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceAuthorizationsTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/MultiTenancyTaskServiceTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/optimize/GetHistoricIdentityLinkLogsForOptimizeTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/repository/diagram/ProcessDiagramParseTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricIdentityLinkLogQueryTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricIdentityLinkLogTest.java
- spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/dom/XmlDomXPathScriptTest.java
Resolve Sonar warnings of type java:S115: Constant names should comply with a naming convention
related to #88
> refactor: Rename constants

- .github/workflows/integration-tests.yml
- .github/workflows/nighly-build.yml
- .github/workflows/release.yml
- jreleaser.yml
- spring-boot-starter/starter-security/pom.xml
Derive variable `OPERATON_DATABASE_VERSION` from property `version.operaton.dbscheme` and use it to qualify the path of the sql-scripts artifact.
Also:
- Fix usage of deprecated value `${version}` by `${project.version}`. This resolves a build warning.
- Change default value for input of nightly build
- Use setup-java in nightly build. The build was effectively using always Java 17 instead of specified versions.
- Fix deprecation of `java` section in `jreleaser.yml`
fixes https://github.com/operaton/operaton/issues/486
> fix: Adjust versioning scheme for SQL scripts package

- engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/context/MultiInstanceTest.java
- engine/src/test/java/org/operaton/bpm/application/impl/event/ProcessApplicationEventListenerTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/FormAuthorizationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/IncidentAuthorizationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/cfg/DatabaseTableSchemaTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/filter/FilterTaskQueryTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/identity/AdminGroupsTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/identity/AdminUsersTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/identity/AuthorizationServiceTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/identity/ReadOnlyIdentityServiceTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/repository/HistoryTimeToLiveDeploymentTest.java
Add assertions to tests lacking them where they make sense. Add `@Test(expected = None.class)` to indicate when only the absense of an exception is required.
relates to: #88
> chore: Fix blocker sonar issues in test code

- engine/src/main/java/org/operaton/bpm/engine/impl/cmd/AbstractInstantiationCmd.java
- engine/src/main/java/org/operaton/bpm/engine/impl/json/ModificationCmdJsonConverter.java
- engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/SingleProcessInstanceModificationAsyncTest.java
- engine/src/test/resources/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.loop.bpmn
related to camunda/camunda-bpm-platform#4507
Backported commit 7bf5c46119 from the camunda-bpm-platform repository.
Original author: Helene <21290204+PHWaechtler@users.noreply.github.com>
> fix(asyncInstanceModification): respect ancestor during startBefore/after cmd execution (#4829)

- test-utils/junit5-extension/src/main/java/org/operaton/bpm/engine/test/junit5/ParameterizedTestExtension.java
- test-utils/junit5-extension/src/test/java/org/operaton/bpm/dmn/engine/test/junit5/ParameterizedTestExtensionTest.java
Add an extension for JUnit 5 to help migration of JUnit 4 Tests like ContainerAuthenticationFilterTest that are annotated with @RunWith(Parameterized.class). The extension implements the same mechanism for JUnit 5 such that the required code changes are minimal.
For the review please take into account the license header. I started a discussion at: 
https://forum.operaton.org/t/license-header-for-new-files/195
relates to #216, #27
> feat(test): New ParameterizedTestExtension

- webapps/assembly/src/main/resources/org/operaton/bpm/cockpit/plugin/base/queries/processDefinition.xml
- webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/ProcessDefinitionRestServiceTest.java
Context: The query selectPDStatistics calculates the total processInstances wrong.
Used-by: ProcessDefinitionRestService#getStatisticsCount
Why: The group by incidentType part of the query should not be used for counting the total process instances.
Tests: The commit adds a test which expects the correct statistics returned when process instances related to incidents with different types are used.
Co-authored-by: Petros Savvidis <petros.savvidis@camunda.com>
Related to https://jira.camunda.com/browse/SUPPORT-24279
Backported commit 586037c29a from the camunda-bpm-platform repository.
Original author: Miklas Boskamp <20189772+mboskamp@users.noreply.github.com>
> fix(webapps/assembly): Fix selectPDStatistics Query

- bom/internal-dependencies/pom.xml
- database/pom.xml
- pom.xml
- webapps/assembly/pom.xml
- moved internal-dependencies BOM to .bom\
- removed duplicate dependency declarations in dependencyManagement
- ensured correct resolution of version.operaton.dbscheme from parent BOM
- fixed duplicate maven-dependency-plugin in integration-test-operaton-run profile"
> Move internal-dependencies (fixes #533)

- engine/src/main/java/org/operaton/bpm/engine/impl/cfg/auth/DefaultAuthorizationProvider.java
- model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/OperatonExtensionsTest.java
- OperatonExtensionsTest: "Annotate this method with JUnit5 '@org.junit.jupiter.api.BeforeEach' or rename it to avoid confusion."
- DefaultAuthorizationProvider: "Refactor this method to not always return the same value."
relates to #511
> chore: Fix two sonar findings with only one finding in code base.

- engine/src/main/java/org/operaton/bpm/engine/impl/util/BitMaskUtil.java
- engine/src/test/java/org/operaton/bpm/engine/impl/util/BitMaskUtilTest.java
@kthoms: Please resolve the following sonar findings manually, as they are false negatives: https://sonarcloud.io/project/issues?impactSeverities=HIGH&impactSoftwareQualities=RELIABILITY&rules=javabugs%3AS6466&issueStatuses=OPEN%2CCONFIRMED&id=operaton_operaton
> chore: fix wrong bitnumber range check (#537)

- clients/java/client/src/main/java/org/operaton/bpm/client/topic/impl/TopicSubscriptionManager.java
- clients/java/client/src/main/java/org/operaton/bpm/client/topic/impl/TopicSubscriptionManagerLogger.java
- clients/java/client/src/test/java/org/operaton/bpm/client/impl/TopicSubscriptionManagerTest.java
We call 'await' in a loop until we run out of time or receive the signal. We exit immediately when receiving the signal and calculate if there is remaining time otherwise.
The 'await' can terminate either by a call from 'signal' or by timing out. Both can happen and are probably ok, but we should at least log the information that a timeout occurred while thread is still running.
If the thread is interrupted we catch the exception and signal the thread to exit gracefully.
relates to: #537
> chore: Rewriting thread behavior to best practices.

- engine/src/test/java/org/operaton/bpm/application/impl/context/ProcessApplicationContextTest.java
- engine/src/test/java/org/operaton/bpm/application/impl/deployment/DeploymentRegistrationTest.java
- engine/src/test/java/org/operaton/bpm/application/impl/deployment/EmptyProcessesXmlTest.java
- engine/src/test/java/org/operaton/bpm/application/impl/deployment/RedeploymentProcessApplicationTest.java
- engine/src/test/java/org/operaton/bpm/application/impl/deployment/RedeploymentRegistrationTest.java
- test-utils/junit5-extension/src/main/java/org/operaton/bpm/engine/test/junit5/ParameterizedTestExtension.java
- test-utils/junit5-extension/src/test/java/org/operaton/bpm/dmn/engine/test/junit5/ParameterizedTestExtensionFieldInjectionTest.java
- Extended ParameteriedTestExtension to support `@Parameter(X)` on fields.
- Added unit test to cover new functionality.
- Migrated first four tests in engine project to JUnit5.
reöates to #566
> chore(test): Migrate first tests in engine from JUnit4 to JUnit5.

- engine-plugins/spin-plugin/src/test/java/org/operaton/spin/plugin/script/SpinScriptTaskSupportWithAutoStoreScriptVariablesTest.java
- engine/src/main/junit5/org/operaton/bpm/engine/test/junit5/ProcessEngineExtension.java
The latest change on ProcessEngineExtension #257b50f9 caused a build problem. The change cleaned up the process engine after test execution. However, it made other tests fail.
This change reverts the change on ProcessEngineExtension and makes sure that the failing test does a proper cleanup.
> build: Revert change in ProcessEngineExtension & fix tests

- parent/pom.xml
All contributions made in this pull request are licensed under the Apache 2.0 license.
fixes #598
> chore(dependencies): Upgrade AssertJ to 3.27

- bom/internal-dependencies/pom.xml
- parent/pom.xml
- Upgrades JUnit to 5.12.1
- Using JUnit BOM for managing all junit related libraries
fixes #574
closes #602
> chore(dependencies): upgrade JUnit to 5.12.1

- bom/internal-dependencies/pom.xml
- distro/run/qa/integration-tests/pom.xml
- distro/run/qa/integration-tests/src/test/java/org/operaton/bpm/run/qa/SqlAvailabilityIT.java
- distro/run/qa/integration-tests/src/test/java/org/operaton/bpm/run/qa/webapps/AbstractWebIT.java
- distro/run/qa/integration-tests/src/test/java/org/operaton/bpm/run/qa/webapps/PluginsRootResourceIT.java
- distro/run/qa/pom.xml
- distro/run/qa/runtime/pom.xml
- engine-dmn/engine/pom.xml
- engine/pom.xml
- parent/pom.xml
- qa/integration-tests-engine/pom.xml
- quarkus-extension/pom.xml
- spin/dataformat-all/pom.xml
- spring-boot-starter/pom.xml
- test-utils/assert/pom.xml
This change fixes 2 problems with the integration test execution:
1) distro operaton: Test `PluginsRootResourceIT` had problems with the old jersey client. Upgraded to newer Jersey.
2) Engine integration tests did not find tests, since JUnitPlatformProvider was used, but tests are still JUnit 4 based.
> Fix integration test execution

- distro/wildfly/assembly/assembly.xml
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/util/DeploymentHelper.java
- qa/integration-tests-webapps/shared-engine/pom.xml
- fix dependency `org.operaton.bpm.javaee:operaton-ejb-client-jakarta` -> `org.operaton.bpm.jakartaee:operaton-ejb-client`
- fix dependency `operaton-webapp-tomcat-jakarta` -> `operaton-webapp-tomcat`
> chore: Fix usage of merged modules

- bom/internal-dependencies/pom.xml
- connect/pom.xml
- distro/run/pom.xml
- distro/run/qa/integration-tests/pom.xml
- distro/run/qa/pom.xml
- distro/run/qa/runtime/pom.xml
- engine-cdi/core/pom.xml
- engine-plugins/pom.xml
- engine-rest/engine-rest-openapi/pom.xml
- engine-rest/engine-rest/pom.xml
- engine/pom.xml
- jakarta-ee/ejb-client/pom.xml
- jakarta-ee/ejb-service/pom.xml
- parent/pom.xml
- pom.xml
- qa/integration-tests-engine/pom.xml
- qa/integration-tests-webapps/pom.xml
- qa/test-old-engine/pom.xml
- qa/tomcat-runtime/pom.xml
- spin/dataformat-json-jackson/pom.xml
- spin/dataformat-xml-dom/pom.xml
- spin/pom.xml
- spring-boot-starter/starter-qa/integration-test-request-scope/pom.xml
- spring-boot-starter/starter/pom.xml
- test-utils/assert/pom.xml
- test-utils/testcontainers/pom.xml
- webapps/assembly/pom.xml
- remove version properties from parent POM for dependencies defined by internal-dependencies
- move dependencies to internal-dependencies
- use internal-dependencies in dependency management for more modules
- remove version attributes from dependencies for managed dependencies
> Build: Dependency cleanup

- .devenv/scripts/build/build-and-run-integration-tests.sh
- jakarta-ee/ejb-client/src/main/java/org/operaton/bpm/application/impl/web/ProcessArchiveServletContextListener.java
- qa/tomcat-runtime/pom.xml
- spin/dataformat-all/pom.xml
- spin/dataformat-all/src/main/resources/META-INF/services/jakarta.xml.bind.JAXBContext
- spin/dataformat-all/src/main/resources/META-INF/services/spinjar.javax.xml.bind.JAXBContext
- spin/dataformat-xml-dom/src/main/java/org/operaton/spin/impl/xml/dom/DomXmlLogger.java
- spin/dataformat-xml-dom/src/main/java/org/operaton/spin/impl/xml/dom/format/spi/DefaultJaxBContextProvider.java
- spin/dataformat-xml-dom/src/test/java/org/operaton/spin/impl/xml/dom/format/spi/DefaultJaxBContextProviderTest.java
- spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/dom/format/spi/EmptyContextProvider.java
This change fixes the shading configuration of the `operaton-spin-dataformat-all` artifact.
It further adds additional debug output when a JAXBContext can't be created due to service loader issues.
> fix: Fix shading of spin dataformat all artifact

- engine/src/test/java/org/operaton/bpm/engine/test/api/history/BatchHistoricDecisionInstanceDeletionUserOperationTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorCmdExceptionTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorExceptionLoggingHandlerTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/ReducedJobExceptionLoggingTest.java
waitForJobExecutorToProcessAllJobs() is flaky. Sometimes jobs are still running
related to #671
> chore: Disable flaky tests

- engine-rest/engine-rest/pom.xml
- parent/pom.xml
Bumping Tomcat version to 10.1.39. We have currently two places where we manage the tomcat version, one is in the engine-rest pom with a comment "pin tomcat version for engine-rest". We need to investigate if this must stay pinned to 10.1.35 (and for what reason and possibly open an issue for it).
I opened the PR to see if the whole test pipelines runs through when we increase the at both places to 10.1.39
> chore: bump Tomcat version to 10.1.39

- qa/integration-tests-engine/src/test/java-wildfly/org/operaton/bpm/integrationtest/util/TestContainer.java
- qa/integration-tests-engine/src/test/resources-wildfly/jboss-deployment-structure.xml
Resolves the problem that the JAXB implementation of JAXBContextFactory could not be loaded
Fixes #713
> fix(dependencies): Add org.glassfish.jaxb dep. to jboss-deployment-structure.xml & include into war

- qa/integration-tests-engine/src/test/java-tomcat/org/operaton/bpm/integrationtest/util/TestContainer.java
- qa/integration-tests-engine/src/test/java-wildfly-servlet/org/operaton/bpm/integrationtest/util/TestContainer.java
- qa/integration-tests-engine/src/test/java-wildfly/org/operaton/bpm/integrationtest/util/TestContainer.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/SpinClassloadingTest.java
- qa/integration-tests-engine/src/test/resources-wildfly/arquillian.xml
- qa/integration-tests-engine/src/test/resources-wildfly/jboss-deployment-structure-spin.xml
- qa/integration-tests-engine/src/test/resources/org/operaton/bpm/integrationtest/functional/ejb/local/jboss-deployment-structure.xml
- qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
- revert 3e3dc94
this has overridden the `jboss-deployment-structure.xml` file that `LocalSFSBInvocationTest` and others needed
- added a spin specific `jboss-deployment-structure.xml` to be used by `SpinClassloadingTest`
> Fix Wildfly integration tests

- engine-rest/engine-rest-openapi/pom.xml
- engine-rest/engine-rest-openapi/src/test/java/org/operaton/bpm/engine/rest/openapi/client/BasicAuthenticationTest.java
- engine-rest/engine-rest-openapi/src/test/java/org/operaton/bpm/engine/rest/openapi/client/DeploymentTest.java
- engine-rest/engine-rest-openapi/src/test/java/org/operaton/bpm/engine/rest/openapi/client/ProcessInstanceTest.java
Start WireMock test on a dynamic port and update to JUnit5
related to #27 
closes #398
> Avoid tests running on port 8080

- engine-rest/assembly/src/main/runtime/jbossas7/webapp/WEB-INF/web.xml
- engine-rest/assembly/src/main/runtime/tomcat/webapp/WEB-INF/web.xml
- engine-rest/assembly/src/main/runtime/was/webapp/WEB-INF/web.xml
- engine-rest/assembly/src/main/runtime/wildfly/webapp/WEB-INF/web.xml
- engine-rest/assembly/src/main/runtime/wls/webapp/WEB-INF/web.xml
- engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/impl/FetchAndLockHandlerImpl.java
- engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/impl/FetchAndLockHandlerTest.java
Related to https://github.com/camunda/camunda-bpm-platform/issues/4885
Backported commit 6154d43341 from the camunda-bpm-platform repository.
> feat(rest): make LockAndFetchHandler blocking queue's capacity configurable

- engine/src/main/java/org/operaton/bpm/application/PostDeploy.java
- engine/src/main/java/org/operaton/bpm/application/impl/ServletProcessApplication.java
- examples/invoice/src/main/java/org/operaton/bpm/example/invoice/InvoiceProcessApplication.java
In a JakartaEE environment the ServletContextListener implementation needs to have to `@WebListener` annotation added.
Updated Javadocs.
closes #696
> fix: Add `@WebListener` to InvoiceProcessApplication

- clients/java/client/src/main/java/org/operaton/bpm/client/impl/ExternalTaskClientBuilderImpl.java
- clients/java/client/src/test/java/org/operaton/bpm/client/impl/ExternalTaskClientBuilderImplTest.java
Related to https://github.com/camunda/camunda-bpm-platform/issues/5112
Backported commit 94bbd59f43 from the camunda-bpm-platform repository.
> fix(xtac): initialize url resolver with null base url

- engine/src/main/java/org/operaton/bpm/engine/impl/history/event/HistoricVariableUpdateEventEntity.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricDetailVariableInstanceUpdateEntity.java
related to camunda/camunda-bpm-platform#4927
Backported commit 8f7940067e from the camunda-bpm-platform repository.
Original author: David Benes <dbenesj@users.noreply.github.com>
> fix(engine): print correct value of processDefinitionId in toString() for events

- webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/security/auth/UserAuthenticationResource.java
- webapps/assembly/src/test/java/org/operaton/bpm/webapp/impl/security/auth/UserAuthenticationResourceTest.java
Related to camunda/camunda-bpm-platform#3739
Backported commit bd17e6619d from the camunda-bpm-platform repository.
> fix(webapp): Handle null authentication as unauthorized

- engine-rest/engine-rest-openapi-generator/src/main/java/org/operaton/bpm/engine/rest/openapi/generator/impl/TemplateParser.java
Just load *.ftl template files instead of loading all files `operaton/engine-rest/engine-rest-openapi/src/main/templates/paths` during the build process. This can lead to an error in the build when a .DS_Store files is placed there by osx.
Fixes #769
> fix: improve build resilience on osx (#769)

- pom.xml
related to camunda/camunda-bpm-platform#4870
Backported commit c92ed54006 from the camunda-bpm-platform repository.
Original author: Helene <21290204+PHWaechtler@users.noreply.github.com>
> chore: bump quarkus version to 3.20.0 (latest LTS)

- engine/src/test/java/org/operaton/bpm/engine/test/api/cfg/IdGeneratorDataSourceTest.java
- engine/src/test/resources/org/operaton/bpm/engine/test/api/cfg/IdGeneratorDataSourceTest.testIdGeneratorDataSource.bpmn20.xml
fix(engine): failing IdGeneratorDataSourceTest
- fixes siliently failing IdGeneratorDataSourceTest
- adds assertion to prevent it from happing again
relates to #500
> fix: failing IdGeneratorDataSourceTest

- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/AbstractManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/AttachmentManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/AuthorizationManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/BatchManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ByteArrayManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/CommentManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/EventSubscriptionManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ExecutionManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ExternalTaskManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricActivityInstanceManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricBatchManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricCaseActivityInstanceManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricCaseInstanceManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricDetailManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricExternalTaskLogManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricIdentityLinkLogManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricIncidentManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricJobLogManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricProcessInstanceManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricTaskInstanceManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricVariableInstanceManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/IdentityInfoManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/IdentityLinkManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/JobDefinitionManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/JobManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/MeterLogManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ProcessDefinitionManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/TaskManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/UserOperationLogManager.java
This change introduces string constants for query paraeters. The class AbstractManager declares constants for parameters used by at least 2 subclasses. Parameters used by only a single implementation are added to the implementation class.
Resolves some warnings regarding string duplication.
> chore: Extract constants for query parameters

- distro/run/core/src/test/java/org/operaton/bpm/run/test/config/https/HttpsConfigurationEnabledTest.java
- distro/run/core/src/test/resources/application-test-https-enabled.yml
- engine-rest/engine-rest/pom.xml
Backport 7e1813e760  from C7
> chore(pom): add support for Spring Boot 3.4.1
> 
> Related to https://github.com/camunda/camunda-bpm-platform/issues/4657
> Backport: chore(pom): add support for Spring Boot 3.4.1

- engine/src/main/java/org/operaton/bpm/engine/query/Query.java
The method Query#list() has been accidently marked for removal with #ec5b1a34 because there was mentioned to use listPage() instead. But list() is widely used and listPage() is only an alternative to consider.
> chore: Revert Query#list() marked for removal

- engine-cdi/src/main/java/org/operaton/bpm/engine/cdi/impl/el/CdiResolver.java
- engine-spring/src/main/java/org/operaton/bpm/engine/spring/ApplicationContextElResolver.java
- engine/src/main/java/org/operaton/bpm/engine/impl/el/AbstractElResolverDelegate.java
- engine/src/main/java/org/operaton/bpm/engine/impl/el/ReadOnlyMapELResolver.java
- engine/src/main/java/org/operaton/bpm/engine/impl/el/VariableContextElResolver.java
- engine/src/main/java/org/operaton/bpm/engine/impl/el/VariableScopeElResolver.java
- engine/src/main/java/org/operaton/bpm/engine/test/mock/MockElResolver.java
- juel/src/main/java/org/operaton/bpm/impl/juel/RootPropertyResolver.java
- juel/src/main/java/org/operaton/bpm/impl/juel/SimpleResolver.java
This method has been marked for removal. It is provided as default method on the interface now. Removed implementations of the method.
relates to #674
relates to #144
> chore: Removed implementations of getFeatureDescriptors

- engine/src/main/java/org/operaton/bpm/engine/history/HistoricVariableInstance.java
- engine/src/main/java/org/operaton/bpm/engine/impl/DeploymentQueryImpl.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/transformer/AbstractCmmnTransformListener.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/transformer/CmmnTransformListener.java
- engine/src/main/java/org/operaton/bpm/engine/impl/history/transformer/CmmnHistoryTransformListener.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricVariableInstanceEntity.java
- engine/src/main/java/org/operaton/bpm/engine/impl/repository/DeploymentBuilderImpl.java
- engine/src/main/java/org/operaton/bpm/engine/impl/repository/ProcessApplicationDeploymentBuilderImpl.java
- engine/src/main/java/org/operaton/bpm/engine/repository/DeploymentBuilder.java
- engine/src/main/java/org/operaton/bpm/engine/repository/DeploymentQuery.java
- engine/src/main/java/org/operaton/bpm/engine/repository/ProcessApplicationDeploymentBuilder.java
- engine/src/test/java/org/operaton/bpm/engine/test/standalone/deploy/TestCmmnTransformListener.java
The following methods have been marked for removal on interfaces, where the implementation to the recommended alternative to use can be implemented in a default method.
Removed implementations of the method in implementing classes.
- org.operaton.bpm.engine.impl.cmmn.transformer.CmmnTransformListener.transformCasePlanModel(org.operaton.bpm.model.cmmn.impl.instance.CasePlanModel, org.operaton.bpm.engine.impl.cmmn.model.CmmnActivity)
- org.operaton.bpm.engine.repository.DeploymentQuery.orderByDeploymenTime
- org.operaton.bpm.engine.history.HistoricVariableInstance.getVariableName
- org.operaton.bpm.engine.history.HistoricVariableInstance.getVariableTypeName
- org.operaton.bpm.engine.repository.DeploymentBuilder.enableDuplicateFiltering()
related to #811
> chore: Make interface methods to default methods which are marked for removal

- distro/wildfly/modules/pom.xml
- distro/wildfly/modules/validate-modules.sh
Add a script `validate-modules.xml` to module distro/wildfly/modules that is executed in the verify phase.
The script checks that refernced files in module.xml descriptors exist.
closes #878
> feat(build): Verify library versions in Wildfly modules

- .github/workflows/integration-build.yml
Aims to fix #596 
I decided to introduce a separate job for change detection whose output can be used to skip other jobs. While we only evalute the result for scheduled jobs, it could be handy for initial testing that the checks are performed for non-scheduled jobs as well.
> Skip nightly builds with no recent changes

- bom/internal-dependencies/pom.xml
This pull request updates commons-fileupload from version 1.5 to 1.6.0 as requested in issue #916, which was flagged by a security scanner.
> chore(bom): upgrade commons-fileupload to 1.6.0 (#916)

- engine/pom.xml
- engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/AsyncContinuationJobHandler.java
- engine/src/test/java/org/operaton/bpm/engine/impl/jobexecutor/AsyncContinuationJobHandlerTest.java
Exception was not raised when given jobConfiguration contained more than 2 segments. The wrong array was compared.
Added unit test.
> fix: AsyncContinuationJobHandler#tokenizeJobConfiguration did not fail for invalid argument

- bom/internal-dependencies/pom.xml
Closes #931
This PR updates the 'commons-compress' dependency to version 1.27.1 to address the reported vulnerability.
The dependency version is now explicitly managed in the `bom/internal-dependencies/pom.xml` file to override the transitive dependency from testcontainers.
> fix(deps): Override commons-compress to 1.27.1

- engine-dmn/feel-scala/src/main/resources/META-INF/services/org.camunda.feel.valuemapper.CustomValueMapper
- engine-plugins/spin-plugin/src/main/resources/META-INF/services/org.camunda.feel.valuemapper.CustomValueMapper
- qa/integration-tests-engine/pom.xml
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/FeelContextDelegate.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/FeelEngineTest.java
- qa/integration-tests-engine/src/test/resources/org/operaton/bpm/integrationtest/functional/spin/feel/feel-spin-input-output.bpmn
- qa/integration-tests-engine/src/test/resources/org/operaton/bpm/integrationtest/functional/spin/feel/feel-spin-json-decision.dmn
- qa/integration-tests-engine/src/test/resources/org/operaton/bpm/integrationtest/functional/spin/feel/feel-spin-process.bpmn
- qa/integration-tests-engine/src/test/resources/org/operaton/bpm/integrationtest/functional/spin/feel/feel-spin-xml-decision.dmn
related to: camunda/camunda-bpm-platform/issues/2384
related to #945 
* feat(engine-plugins): Support FEEL Scala Engine
* feat(feel-scala): register the FEEL JavaValueMapper SPI
* feat(feel): configure wildfly distro
* camunda-engine-plugin-spin should be optional
related to: camunda/camunda-bpm-platform/issues/2384 ---------
Co-authored-by: Tassilo Weidner <3015690+tasso94@users.noreply.github.com>
Co-authored-by: yanavasileva <yanavasileva@users.noreply.github.com>
Backported commit 4ad576e8d5 from the camunda-bpm-platform repository.
> feat(engine-plugins): Support FEEL Scala Engine (#5018)

- .devenv/scripts/build/build-and-run-database-update-tests.sh
Causes a build error, because "mariadb" is not recognized as a valid value
> Remove trailing comma in VALID_DATABASES

- engine/src/main/java/org/operaton/bpm/engine/impl/application/ProcessApplicationManager.java
- engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/handler/ItemHandler.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/database/PurgeDatabaseTest.java
- webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/security/filter/Authorization.java
Refactors the logic behind checking whether a StringBuilder is empty, by using `isEmpty()`
Closes #1003
> refactor: use isEmpty() to check whether a StringBuilder is empty or not

- distro/wildfly/assembly/assembly.xml
The /lib folder in the distribution contains redundant libraries, which are already included in the distro in modules.
Reduces the size of the tar.gz file from 451 MB to 415 MB (-46 MB).
> build(wildfly): Remove /lib folder from distro

- distro/license-book/assembly.xml
- distro/run/assembly/assembly.xml
- distro/run/distro/assembly.xml
- distro/sql-script/assembly.xml
- distro/tomcat/assembly/assembly.xml
- distro/tomcat/distro/assembly.xml
- distro/wildfly/assembly/assembly.xml
- distro/wildfly/distro/assembly.xml
- engine-rest/assembly/assembly-classes.xml
- engine-rest/assembly/assembly-sources.xml
- engine-rest/assembly/assembly-tests.xml
- engine-rest/assembly/assembly-war-tomcat.xml
- engine-rest/assembly/assembly-war-wildfly.xml
- webapps/assembly/assembly.xml
This PR resolves issue #1014.
This PR updates all assembly.xml files with outdated xmlns decalrations
I confirm that my contribution and following ones comply with the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0)
and the [Code of Conduct](https://github.com/operaton/operaton/blob/main/CODE_OF_CONDUCT.md)
closes #1014
> Update xmlns for assembly.xml files

- distro/wildfly/modules/pom.xml
Import the Groovy BOM for dependency management. This overloads implicit behaviour that could lead for pulling a newer Groovy version than defined by parent/pom.xml.
closes #1049
> chore(deps): Pin Groovy version for Wildfly modules

- parent/pom.xml
Bump Groovy to 4.0.28 ([Release Notes](https://groovy-lang.org/changelogs/changelog-4.0.28.html))
> chore(deps): Upgrade Groovy to 4.0.28

- engine/src/main/java/org/operaton/bpm/engine/impl/HistoricDetailQueryProperty.java
- engine/src/main/java/org/operaton/bpm/engine/impl/HistoricExternalTaskLogQueryProperty.java
- engine/src/main/java/org/operaton/bpm/engine/impl/HistoricIdentityLinkLogQueryProperty.java
- engine/src/main/java/org/operaton/bpm/engine/impl/HistoricIncidentQueryProperty.java
- engine/src/main/java/org/operaton/bpm/engine/impl/HistoricJobLogQueryProperty.java
- engine/src/main/java/org/operaton/bpm/engine/impl/HistoricProcessInstanceQueryProperty.java
- engine/src/main/java/org/operaton/bpm/engine/impl/HistoricTaskInstanceQueryProperty.java
- engine/src/main/java/org/operaton/bpm/engine/impl/HistoricVariableInstanceQueryProperty.java
- engine/src/main/java/org/operaton/bpm/engine/impl/IncidentQueryProperty.java
- engine/src/main/java/org/operaton/bpm/engine/impl/JobDefinitionQueryProperty.java
- engine/src/main/java/org/operaton/bpm/engine/impl/JobQueryProperty.java
- engine/src/main/java/org/operaton/bpm/engine/impl/ProcessDefinitionQueryProperty.java
- engine/src/main/java/org/operaton/bpm/engine/impl/ProcessInstanceQueryProperty.java
- engine/src/main/java/org/operaton/bpm/engine/impl/TaskQueryProperty.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/entity/runtime/CaseInstanceQueryProperty.java
Refactors constant definitions by replacing `interface` constants with
`final` utility classes and static final fields. Adds private constructors
to prevent instantiation.
Updated 15 of 40 classes:
- HistoricDetailQueryProperty
- HistoricExternalTaskLogQueryProperty
- HistoricIdentityLinkLogQueryProperty
- HistoricIncidentQueryProperty
- HistoricJobLogQueryProperty
- HistoricProcessInstanceQueryProperty
- HistoricTaskInstanceQueryProperty
- HistoricVariableInstanceQueryProperty
- IncidentQueryProperty
- JobDefinitionQueryProperty
- JobQueryProperty
- ProcessDefinitionQueryProperty
- ProcessInstanceQueryProperty
- TaskQueryProperty
- HistoricCaseInstanceQueryProperty
related to #1059
> refactor(engine): convert constant interfaces to utility classes (16-30/40)

- rewrite.yml
Adds a style definition for Operaton projects that can be used to harmonize the Java imports.
related to #1104 
For testing execute
```
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.activeRecipes=org.openrewrite.java.OrderImports -Drewrite.exportDatatables=true -Drewrite.activeStyles=org.operaton.style.OperatonJavaStyle -f commons
```
> feat(build): Add rewrite.yml

- .github/jreleaser/changelog.tpl
- database/pom.xml
- qa/tomcat-runtime/pom.xml
- qa/wildfly-runtime/src/main/common/modules/com/microsoft/sqlserver/mssql-jdbc/main/module.xml
- qa/wildfly-runtime/src/main/common/modules/com/mysql/mysql-connector-j/main/module.xml
- qa/wildfly-runtime/src/main/common/modules/com/oracle/database/jdbc/ojdbc11/main/module.xml
- qa/wildfly-runtime/src/main/common/modules/org/mariadb/jdbc/mariadb-java-client/main/module.xml
- SQL Server: 12.10.0.jre8 → 12.10.1.jre11
- MySQL: 9.3.0 → 9.4.0
- Oracle: 23.5.0.24.07 → 23.9.0.25.07
- MariaDB: 1.7.6 → 1.8.0
- Update WildFly module JAR references
- Clean up dependency management in tomcat-runtime
Files updated:
- database/pom.xml: Update version properties
- qa/tomcat-runtime/pom.xml: Clean up dependency management
- qa/wildfly-runtime module.xml files: Update JAR filenames
Issue #1122
> feat: upgrade JDBC drivers to latest versions

- qa/performance-tests-engine/pom.xml
Update tomcat-jdbc and tomcat-juli dependencies to use the globally defined Tomcat version in the project.
closes #1136
> fix: Update tomcat-jdbc and tomcat-juli dependencies versions

- model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/impl/instance/operaton/OperatonListImpl.java
Refactored the anonymous Collection implementation in org.operaton.bpm.model.bpmn.impl.instance.operaton.OperatonListImpl to a dedicated static inner class, improving code readability and maintainability.
closes #1147
> refactor: move anonymous Collection in OperatonListImpl to inner class

- clients/java/client/src/it/java/org/operaton/bpm/client/rule/EngineRule.java
- distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/config/ManagedProcessEngineMetadata.java
- distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/service/ProcessApplicationDeploymentService.java
- engine/src/main/java/org/operaton/bpm/container/impl/ContainerIntegrationLogger.java
- engine/src/main/junit-shared/org/operaton/bpm/engine/impl/test/TestHelper.java
- engine/src/main/junit-shared/org/operaton/bpm/engine/test/util/ExecutionTreeProcessDefinitionIdAssertion.java
- engine/src/test/java/org/operaton/bpm/engine/test/persistence/DatabaseNamingConsistencyTest.java
- qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/XmlListSerializable.java
- webapps/assembly/src/main/runtime/test/java/org/operaton/bpm/pa/rest/TestServlet.java
- webapps/assembly/src/test/java/org/operaton/bpm/webapp/impl/engine/WebappsDatabaseNamingConsistencyTest.java
All instances of StringBuilder.append() with string concatenation have been refactored to use multiple append calls for improved readability.
closes #1157
> refactor: remove string concatenation from StringBuilder.append() calls

- engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/DefaultDmnEngineConfiguration.java
- engine-dmn/feel-scala/src/main/java/org/operaton/bpm/dmn/feel/impl/scala/ScalaFeelEngine.java
- engine-dmn/feel-scala/src/main/java/org/operaton/bpm/dmn/feel/impl/scala/ScalaFeelEngineFactory.java
- engine-dmn/feel-scala/src/test/java/org/operaton/bpm/dmn/feel/impl/scala/ScalaFeelEngineTest.java
Refactored the Scala FEEL engine integration by replacing the deprecated `org.camunda.feel.FeelEngine.Builder` with the new `FeelEngineBuilder` and `FeelEngineApi`. This change ensures compatibility with the latest FEEL APIs and improves maintainability and clarity of the engine integration.
Closes #863
The `FeelEngine.Builder` class has been deprecated and replaced by `FeelEngineBuilder` with the `FeelEngineApi` interface. Migrating to the newer API improves long-term supportability, aligns with current FEEL best practices, and removes the dependency on legacy internals.
- Replaced all usages of the deprecated `FeelEngine.Builder` with `FeelEngineBuilder.forJava()`.
- Refactored `ScalaFeelEngine` to internally use `FeelEngineApi` instead of `FeelEngine`.
- Updated method implementations …
> refactor(feel-scala): replace deprecated Builder with FeelEngineBuilder API

- connect/pom.xml
- database/pom.xml
- engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.db2.create.engine.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.h2.create.engine.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.mariadb.create.engine.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.mssql.create.engine.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.mysql.create.engine.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.oracle.create.engine.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.postgres.create.engine.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/liquibase/operaton-changelog.xml
- engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/db2_engine_7.23_to_7.24.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/h2_engine_7.23_to_7.24.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/mariadb_engine_7.23_to_7.24.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/mssql_engine_7.23_to_7.24.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/mysql_engine_7.23_to_7.24.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/oracle_engine_7.23_to_7.24.sql
- engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/postgres_engine_7.23_to_7.24.sql
- qa/test-db-instance-migration/pom.xml
- qa/test-db-instance-migration/test-fixture-724/pom.xml
- qa/test-db-instance-migration/test-fixture-724/src/main/java/org/operaton/bpm/qa/upgrade/TestFixture.java
- qa/test-db-instance-migration/test-fixture-724/src/main/resources/operaton.cfg.xml
- qa/test-old-engine/pom.xml
- spin/pom.xml
This PR will backport 694726279a  from camunda-bpm-platform
>     chore(release): prepare codebase for 7.24 development (#5071)
>     
>         * chore(release): prepare codebase for 7.24 development
>     
>         Related to https://github.com/camunda/camunda-bpm-platform/issues/4713
>     
>         * Fix test fixture 723 version
HEADS-UP: Do not merge before 1.0.0-beta-5 is released. This pr needs to be updated after operaton 1.0.0-beta-5
|Operaton Version | Db Schema Version|
|------------------|--------------------|
|1.0.0-beta-5 | 7.23.0|
|1.0.0-rc-1 | 7.24.0|
> Backport 694726279a (prepare codebase for db 7.24.0 / 1.0.0-rc-1 development)

- pom.xml
- maven-failsafe-plugin 3.5.3 -> 3.5.4
- maven-shade-plugin    3.6.0 -> 3.6.1
- maven-surefire-plugin 3.5.3 -> 3.5.4
- cargo-maven3-plugin   1.10.21 -> 1.10.22
- versions-maven-plugin 2.18.0 -> 2.19.0
> chore(build): Update Maven plugins

- engine/src/main/java/org/operaton/bpm/engine/history/HistoricVariableInstanceQuery.java
- engine/src/main/java/org/operaton/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
- engine/src/main/java/org/operaton/bpm/engine/impl/HistoricVariableInstanceQueryImpl.java
- engine/src/main/java/org/operaton/bpm/engine/impl/HistoricVariableInstanceQueryProperty.java
- engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetActivityInstanceCmd.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ActivityInstanceImpl.java
- engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/TransitionInstanceImpl.java
- engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/HistoricVariableInstance.xml
- engine/src/test/java/org/operaton/bpm/engine/test/api/queries/QueryByIdAfterTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/bpmn/subprocess/SubProcessTest.java
- engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricVariableInstanceTest.java
* add HistoricVariableInstanceQuery orderByVariableId
* add TransitionInstanceImpl set/getSubProcessInstanceId
closes #1167
---
Related to https://github.com/camunda/camunda-bpm-platform/issues/4993
originally-authored-by: Tassilo Weidner <3015690+tasso94@users.noreply.github.com>
originally-authored-by: joaquinfelici
Backported commit https://github.com/camunda/camunda-bpm-platform/commit/1d054cf757 Backported commit https://github.com/camunda/camunda-bpm-platform/commit/320e9f6dd9
> feat(engine): extend queries with afterId filter

- bom/internal-dependencies/pom.xml
- pom.xml
Updates `org.springframework:spring-framework-bom` from 6.2.10 to 6.2.11
Release notes: https://github.com/spring-projects/spring-framework/releases/tag/v6.2.11
> chore(deps): Upgrade Spring to 6.2.11

- .github/scripts/install-chrome-and-driver.sh
- .github/workflows/integration-build.yml
- distro/run/qa/integration-tests/src/test/java/org/operaton/bpm/run/qa/webapps/AbstractWebappUiIT.java
- distro/run/qa/pom.xml
- distro/run/qa/runtime/pom.xml
- engine-rest/engine-rest/pom.xml
- qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/AbstractWebappUiIntegrationTest.java
- qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/TestProperties.java
- qa/integration-tests-webapps/pom.xml
- qa/integration-tests-webapps/shared-engine/pom.xml
- qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
- spring-boot-starter/starter-qa/integration-test-webapp/pom.xml
- spring-boot-starter/starter-qa/integration-test-webapp/runtime/pom.xml
Verfies that #930 was fixed
Summary:
* Changed default context path for Web Apps to `/operaton` from `/camunda`
* Added newest version of Maven Cargo plugin which is needed for the latest Wildfly container
* Added `operaton-commons-utils` as dependency to engine-rest, because it depends on the Collection Utils which were moved there
* Removed handling of Chromedriver versions from the build process 
* Increased logging details for Maven Cargo Plugin
* Added bash script to install Chrome and Chromedriver in the latest version in GitHub Actions
> Make Integration Tests for Web Apps runnable

- bom/operaton-bom/pom.xml
- bom/operaton-only-bom/pom.xml
- clients/java/pom.xml
Upgrade all non-HTTPS URLs in Maven pom.xml files to their secure HTTPS counterparts to improve security and follow modern web standards.
I confirm that my contribution and following ones comply with the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0)
and the [Code of Conduct](https://github.com/operaton/operaton/blob/main/CODE_OF_CONDUCT.md).
related to #1325
> fix(maven): upgrade unsecure URLs to HTTPS

- .devenv/scripts/build/build-and-run-integration-tests.sh
- .devenv/scripts/build/build.sh
I'm using Maven Daemon locally on my machine to speed up builds for integration testing, often cutting the test times in half.
I added a parameter to the script, so developers can choose to use the existing scripts either with the maven wrapper (default) or with Maven daemon:
`.devenv/scripts/build/build-and-run-integration-tests.sh --testsuite=engine --distro=tomcat --db=h2 --daemon`
https://github.com/user-attachments/assets/a604bdfb-8e4e-422c-af6a-e364444d96a9
> Enable users to start integration build scripts with mvnd

- distro/run/core/src/main/java/org/operaton/bpm/run/OperatonBpmRunProcessEngineConfiguration.java
- distro/run/core/src/test/java/org/operaton/bpm/run/test/TelemetryDataTest.java
- engine/src/main/java/org/operaton/bpm/engine/impl/diagnostics/OperatonIntegration.java
This PR renames two constants to align them with the Operaton renaming and to remove the remaining CAMUNDA_* references:
•	CAMUNDA_EJB_SERVICE → OPERATON_EJB_SERVICE
•	CAMUNDA_BPM_RUN → OPERATON_BPM_RUN
These constants were previously only used in the telemetry code, so they are unlikely to be consumed externally. Renaming them ensures consistency with other changes where CAMUNDA_* identifiers were replaced by their OPERATON_* equivalents.
> chore(engine): rename OperatonIntegration constants and references
