CONTRIBUTING.md, commons/README.md, distro/tomcat/assembly/src/conf/server.xml, qa/tomcat-runtime/src/main/conf/server.xml, qa/tomcat9-runtime/src/main/conf/server.xml, qa/wildfly-runtime/pom.xml, qa/wildfly26-runtime/pom.xml, webapps/README.md
I have found some issues which were left from initial renaming.
=> Fix wordings which failed by renaming from original to new name

pom.xml
=> Change issueManagement to Operaton GitHub issues

clients/java/pom.xml, commons/pom.xml, connect/pom.xml, engine-dmn/pom.xml, freemarker-template-engine/pom.xml, model-api/bpmn-model/pom.xml, model-api/cmmn-model/pom.xml, model-api/dmn-model/pom.xml, model-api/xml-model/pom.xml, parent/pom.xml, pom.xml, spin/pom.xml, spring-boot-starter/pom.xml, webapps/assembly/pom.xml
- set inceptionYear to 2024 in root and parent POM
- delete inceptionYear from submodules
Fixes #39
=> [build] Update inceptionYear attribute

README.md
I have included a note in the readme so that users have information about the compatibility of the BPMN models. As long as we don't have an Operaton modeller.
=> Add modeller compatibility information into main README.md file.

pom.xml
=> Manage version of maven-shade-plugin via pluginManagement

engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoryCleanupTest.java
Temporary disable the failing test.
=> [#60] Disable HistoryCleanupTest#testLessThanThresholdOutsideBatchWindowAfterMidnight()

README.md
Can be viewed [here](https://github.com/kthoms/operaton/tree/issues/56-maven-badge?tab=readme-ov-file)
Fixes #56
=> [#56] Add badge for Maven Central

connect/pom.xml, distro/run/qa/pom.xml, engine-dmn/pom.xml, internal-dependencies/pom.xml, parent/pom.xml, spin/dataformat-all/pom.xml, test-utils/assert/core/pom.xml, test-utils/junit5-extension-dmn/pom.xml, test-utils/junit5-extension/pom.xml
=> [#53] revert JUnit properties rename

test-utils/archunit/src/main/java/org/operaton/bpm/engine/test/archunit/ArchRulesTest.java
=> chore: Enable ArchUnit tests again #69

.github/workflows/build.yml, pom.xml
=> chore: Enabled static analysis with SonarQube

README.md, distro/wildfly/pom.xml, distro/wildfly26/pom.xml, engine-spring/core-6/pom.xml, pom.xml, qa/wildfly-runtime/pom.xml, qa/wildfly26-runtime/pom.xml, spring-boot-starter/pom.xml
=> Raise minimal Java version to 17

README.md
Also add logo for maven-central
https://github.com/kthoms/operaton/tree/docs/sonar-badge
=> [#66] Add Sonarqube badge

CODE_OF_CONDUCT.md
The text is taken from [Contributor Covenant](https://www.contributor-covenant.org/version/2/0/code_of_conduct/).
Fixes #49
=> [#49] Create CODE_OF_CONDUCT.md

.github/ISSUE_TEMPLATE/bug_report.md, README.md, TESTING.md
After a small discussion about writing Operaton we have changed all upercase OPERATON to Operaton.
=> Rename OPERATON to Operaton

.github/workflows/build.yml
=> Update the GitHub dependency graph when building the main branch

qa/tomcat-runtime/pom.xml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4434
=> chore(tomcat-runtime): Fix webapp-IT-tomcat-10-h2 failing tests

engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/OperatonFormDefinition.xml, engine/src/test/java/org/operaton/bpm/engine/test/form/deployment/OperatonFormDefinitionDeploymentTest.java
Related to https://github.com/camunda/camunda-bpm-platform/issues/4492
This is a backported commit from camunda-bpm-platform. Original author: Piyush <piyushaswani55@gmail.com>
=> fix(engine): increment version for form definition on redeploy

webapps/frontend/webpack.common.js
related to https://github.com/camunda/camunda-bpm-platform/issues/4404
Backported commit df06ab66ad from the camunda-bpm-platform repository.
=> fix(webapp): fix formjs date picker error (#4456)

engine/pom.xml
Related-to: https://github.com/camunda/team-automation-platform/issues/163
Backported commit f37877b822 from the camunda-bpm-platform repository.
=> chore(engine): Remove Unnecessary JBoss Artifacts

engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/HistoricActivityInstance.xml, engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/HistoricCaseActivityInstance.xml, engine/src/test/java/org/operaton/bpm/engine/test/persistence/DatabaseNamingConsistencyTest.java, webapps/assembly/src/main/resources/org/operaton/bpm/cockpit/plugin/base/queries/processDefinition.xml, webapps/assembly/src/test/java/org/operaton/bpm/webapp/impl/engine/WebappsDatabaseNamingConsistencyTest.java
Related to https://github.com/camunda/camunda-bpm-platform/issues/4525
Backported commit c28764a0ad from the camunda-bpm-platform repository.
Original author: Miklas Boskamp <20189772+mboskamp@users.noreply.github.com>
=> fix(db): ensure case-sensitive DB collations work (#4542)

parent/pom.xml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4346
Backported commit e4c392c18f from the camunda-bpm-platform repository.
=> chore(parent): Bump Quarkus to Version 3.85

engine/src/main/java/org/operaton/bpm/application/impl/JakartaServletProcessApplicationDeployer.java, engine/src/main/java/org/operaton/bpm/application/impl/ServletProcessApplicationDeployer.java, engine/src/main/java/org/operaton/bpm/container/impl/deployment/PostDeployInvocationStep.java, engine/src/main/java/org/operaton/bpm/container/impl/deployment/PreUndeployInvocationStep.java, engine/src/main/java/org/operaton/bpm/container/impl/deployment/scanning/ClassPathProcessApplicationScanner.java, engine/src/main/java/org/operaton/bpm/container/impl/deployment/util/InjectionUtil.java, engine/src/main/java/org/operaton/bpm/engine/impl/AbstractQuery.java, engine/src/main/java/org/operaton/bpm/engine/impl/DefaultPriorityProvider.java, engine/src/main/java/org/operaton/bpm/engine/impl/HistoricDetailQueryImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/CallableElementActivityBehavior.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ClassDelegateActivityBehavior.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/EventBasedGatewayActivityBehavior.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/InclusiveGatewayActivityBehavior.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ScriptTaskActivityBehavior.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ServiceTaskDelegateExpressionActivityBehavior.java
Fixing all Sonar issues of type S6201 in module engine. Part of #85
=> chore: Fix instanceof check and cast with pattern matching

connect/http-client/src/main/java/org/operaton/connect/httpclient/impl/AbstractHttpConnector.java, connect/http-client/src/main/java/org/operaton/connect/httpclient/impl/HttpConnectorLogger.java, connect/http-client/src/test/java/org/operaton/connect/httpclient/HttpRequestTest.java, connect/http-client/src/test/java/org/operaton/connect/httpclient/HttpResponseTest.java
related to https://github.com/camunda/camunda-bpm-platform/issues/4241
Backported commit 42c77fc8d9 from the camunda-bpm-platform repository. Original author: Shenoy, Nandan <nandan.shenoy@fmr.com>
=> feat(connect): add http connector response error handling

distro/wildfly/assembly/src/wildfly/standalone-full.xml, distro/wildfly/assembly/src/wildfly/standalone.xml, parent/pom.xml, qa/wildfly-runtime/src/main/wildfly/domain/configuration/domain.xml, qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
https://github.com/camunda/camunda-bpm-platform/issues/4164
Backported commit 7ba3216591 from the camunda-bpm-platform repository.
Original author: yanavasileva <yanavasileva@users.noreply.github.com>
=> feat(wildfly): add support for WildFly 33 (#4488)

database/pom.xml
elated-to: https://github.com/camunda/camunda-bpm-platform/issues/4347
Backported commit b8345194de from the camunda-bpm-platform repository.
=> chore(database): Bump H2 to 2.3.232 R

parent/pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/4533
Backported commit 5f44d4ff1b from the camunda-bpm-platform repository.
=> chore(deps): bump tomcat to versions 9.0.90

database/pom.xml, engine/src/main/java/org/operaton/bpm/engine/impl/db/sql/DbSqlSession.java, engine/src/test/java/org/operaton/bpm/engine/test/persistence/ConnectionPersistenceExceptionTest.java, qa/test-old-engine/pom.xml
related to camunda/camunda-bpm-platform#4001
Backported commit 95ad993bb1 from the camunda-bpm-platform repository.
=> chore(databases): add support for oracle 23ai (#4522)

engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/DefaultDmnEngineConfiguration.java, engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/el/VariableContextScriptBindings.java, engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/evaluation/ExpressionEvaluationHandler.java, engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/hitpolicy/AbstractCollectNumberHitPolicyHandler.java, engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/metrics/DmnEngineMetricCollectorWrapper.java, engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/type/BooleanDataTypeTransformer.java, engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/type/DateDataTypeTransformer.java, engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/type/DoubleDataTypeTransformer.java, engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/type/IntegerDataTypeTransformer.java, engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/type/LongDataTypeTransformer.java
Next batch of fixes for S6201 in engine-dmn/engine
=> chore(sonar): Fix instanceof check and cast with pattern matching

clients/java/client/src/main/java/org/operaton/bpm/client/impl/EngineClient.java, clients/java/client/src/main/java/org/operaton/bpm/client/task/impl/ExternalTaskImpl.java, clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/value/DeferredFileValueImpl.java, clients/java/client/src/main/java/org/operaton/bpm/client/variable/value/DeferredFileValue.java
related to: #4523
Backported commit f06cb967dd from the camunda-bpm-platform repository.
Original author: Gergely Juhasz <gergely.juhasz@camunda.com>
=> fix(client): load local file variable (#4594)

webapps/frontend/package-lock.json, webapps/frontend/package.json
related to camunda/camunda-bpm-platform#4613
Backported commit 8de6e2d4da from the camunda-bpm-platform repository.
=> chore(webapps): bump webpack to the latest version  (#4614)

parent/pom.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4551
Backported commit 1e800652da from the camunda-bpm-platform repository.
=> chore(engine): Bump Spring Framework

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-instance.ftl, engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java, engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricProcessInstanceRestServiceQueryTest.java, engine/src/main/java/org/operaton/bpm/engine/history/HistoricProcessInstanceQuery.java, engine/src/main/java/org/operaton/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java, engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml, engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceTest.java, engine/src/test/resources/org/operaton/bpm/engine/test/api/runtime/failingProcessAfterUserTaskCreateOneIncident.bpmn20.xml
related to: #4587
---------
Co-authored-by: Tassilo Weidner <3015690+tasso94@users.noreply.github.com>
Backported commit 5d02cd39bc from the camunda-bpm-platform repository.
Original author: Gergely Juhasz <gergely.juhasz@camunda.com>
=> feat(api): add filter on incidentIdIn for HistoricProcessInstanceQuery

pom.xml
With #951aef77 the wrong property slipped in.
=> [#78] Fix sonar.coverage.jacoco.xmlReportPaths

CONTRIBUTING.md
- CONTRIBUTING.md
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4467
Backported commit 233c9820eb from the camunda-bpm-platform repository.
=> chore: Remove Swagger References

bom/operaton-only-bom/pom.xml, clients/java/client/pom.xml, distro/run/assembly/assembly.xml, distro/run/assembly/pom.xml, distro/run/assembly/resources/run.bat, distro/run/assembly/resources/run.sh, distro/run/modules/oauth2/pom.xml, distro/run/modules/oauth2/src/main/java/org/operaton/bpm/spring/boot/starter/security/OperatonBpmSpringSecurityDisableAutoConfiguration.java, distro/run/modules/oauth2/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, distro/run/pom.xml, distro/run/qa/integration-tests/src/test/java/org/operaton/bpm/run/qa/ComponentAvailabilityIT.java, parent/pom.xml, spring-boot-starter/pom.xml, spring-boot-starter/starter-security/pom.xml, spring-boot-starter/starter-security/src/test/java/my/own/custom/spring/boot/project/SampleApplication.java, spring-boot-starter/starter-security/src/test/java/my/own/custom/spring/boot/project/SamplePermitAllApplication.java, spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/OperatonBpmSampleApplicationTest.java, spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/OperatonBpmSamplePermitAllApplicationTest.java, spring-boot-starter/starter-security/src/test/resources/logback-test.xml
related to https://github.com/camunda/camunda-bpm-platform/issues/4451
Backported commit 2368e55663 from the camunda-bpm-platform repository.
=> feat(spring-boot/run): add spring security & oauth2 modules (#4478)

webapps/frontend/public/app/admin/locales/de.json, webapps/frontend/public/app/cockpit/locales/de.json, webapps/frontend/public/app/tasklist/locales/de.json, webapps/frontend/public/app/welcome/locales/de.json
Related to https://github.com/camunda/camunda-bpm-platform/issues/4266#event-14411902807
Backported commit 818d03cd25 from the camunda-bpm-platform repository.
=> chore(release): update German translation 

clients/java/client/src/it/java/org/operaton/bpm/client/variable/FileSerializationIT.java, clients/java/client/src/main/java/org/operaton/bpm/client/task/impl/ExternalTaskImpl.java, clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/TypedValues.java, clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/VariableValue.java, clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/value/DeferredFileValueImpl.java, clients/java/client/src/main/java/org/operaton/bpm/client/variable/value/DeferredFileValue.java, clients/java/client/src/test/java/org/operaton/bpm/client/task/ExternalTaskImplTest.java
related to: camunda/camunda-bpm-platform#4523
Co-authored-by: Tassilo Weidner <3015690+tasso94@users.noreply.github.com>
Backported commit 30ece1819d from the camunda-bpm-platform repository. Original author: Gergely Juhasz <gergely.juhasz@camunda.com>"
=> fix(client) don't expose executionId to public API (#4611)

distro/jboss/pom.xml, distro/run/pom.xml, distro/run/qa/pom.xml, distro/tomcat/pom.xml, distro/wildfly/pom.xml, pom.xml, spring-boot-starter/pom.xml, spring-boot-starter/starter-qa/pom.xml
Fixes #152
**Testing Instruction**
```
mvn help:all-profiles | grep 'Active' | awk '{print $3}' | sort -u | grep distro
```
This will result in:
```
distro
distro-run
distro-serverless
distro-starter
distro-tomcat
distro-webjar
distro-wildfly
```
=> chore(build): Merge profile 'distro-ce' into 'distro' (#152)

spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OAuth2Properties.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OperatonSpringSecurityOAuth2AutoConfiguration.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/OAuth2GrantedAuthoritiesMapper.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/OAuth2IdentityProvider.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/OAuth2IdentityProviderFactory.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/OAuth2IdentityProviderPlugin.java
related to https://github.com/camunda/camunda-bpm-platform/issues/4453
Backported commit a485ee9828 from the camunda-bpm-platform repository.
=> feat(run): add oauth2 identity provider (#4570)

spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OperatonSpringSecurityOAuth2AutoConfiguration.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/AuthorizeTokenFilter.java
related to https://github.com/camunda/camunda-bpm-platform/issues/4585
Backported commit f8142ef3e1 from the camunda-bpm-platform repository.
=> feat(oauth2): revalidate access tokens (#4603)

spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OAuth2Properties.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OperatonSpringSecurityOAuth2AutoConfiguration.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/SsoLogoutSuccessHandler.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/plugin/SsoLogoutPluginConstants.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/plugin/admin/SsoLogoutAdminPlugin.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/plugin/admin/SsoLogoutAdminPluginRootResource.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/plugin/cockpit/SsoLogoutCockpitPlugin.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/plugin/cockpit/SsoLogoutCockpitPluginRootResource.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/plugin/tasklist/SsoLogoutTasklistPlugin.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/plugin/tasklist/SsoLogoutTasklistPluginRootResource.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/plugin/welcome/SsoLogoutWelcomePlugin.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/plugin/welcome/SsoLogoutWelcomePluginRootResource.java, spring-boot-starter/starter-security/src/main/resources/META-INF/services/org.operaton.bpm.admin.plugin.spi.AdminPlugin, spring-boot-starter/starter-security/src/main/resources/META-INF/services/org.operaton.bpm.cockpit.plugin.spi.CockpitPlugin, spring-boot-starter/starter-security/src/main/resources/META-INF/services/org.operaton.bpm.tasklist.plugin.spi.TasklistPlugin, spring-boot-starter/starter-security/src/main/resources/META-INF/services/org.operaton.bpm.welcome.plugin.spi.WelcomePlugin, spring-boot-starter/starter-security/src/main/resources/plugin-webapp/sso-logout-plugin/app/plugin.js
https://github.com/camunda/camunda-bpm-platform/issues/4455
Backported commit 8d843b4bee from the camunda-bpm-platform repository.
=> feat(oauth2): add sso logout support (#4604)

spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OAuth2Properties.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/AuthorizeTokenFilter.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/SsoLogoutSuccessHandler.java
https://github.com/camunda/camunda-bpm-platform/issues/4455
Backported commit 32eb28133f from the camunda-bpm-platform repository.
=> feat(oauth2): improve logging with token name (#4638)

spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OAuth2Properties.java, spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OperatonSpringSecurityOAuth2AutoConfiguration.java
https://github.com/camunda/camunda-bpm-platform/issues/4583
Backported commit 8af91b8aa0 from the camunda-bpm-platform repository.
=> feat(oauth2): enable identity provider by default (#4643)

engine/src/test/java/org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.java
=> fix(engine,tests): Proper setup for locale depending test (#198)

engine/src/main/java/org/operaton/bpm/engine/ManagementService.java, engine/src/main/java/org/operaton/bpm/engine/authorization/Groups.java, engine/src/main/java/org/operaton/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmd/UnlockUserCmd.java, engine/src/main/java/org/operaton/bpm/engine/impl/identity/WritableIdentityProvider.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/AuthorizationManager.java, engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/DeploymentAuthorizationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/ManagementAuthorizationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/SchemaLogQueryAuthorizationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/history/HistoryCleanupAuthorizationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceAuthorizationsTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyCommandTenantCheckTest.java, examples/invoice/src/main/java/org/operaton/bpm/example/invoice/DemoDataGenerator.java, examples/invoice/src/main/java/org/operaton/bpm/example/invoice/InvoiceApplicationHelper.java, qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/authorization/AuthorizationTest.java, spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/configuration/impl/custom/CreateAdminUserConfiguration.java, webapps/assembly/src/main/java/org/operaton/bpm/admin/impl/web/SetupResource.java, webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/engine/ProcessEnginesFilter.java, webapps/assembly/src/main/runtime/develop/java/org/operaton/bpm/pa/DevProcessApplication.java, webapps/assembly/src/main/runtime/test/java/org/operaton/bpm/pa/rest/TestServlet.java, webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/tenantcheck/IncidentRestServiceTenantCheckTest.java, webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/tenantcheck/ProcessDefinitionResourceTenantCheckTest.java, webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/tenantcheck/ProcessDefinitionRestServiceTenantCheckTest.java, webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/tenantcheck/ProcessInstanceResourceTenantCheckTest.java, webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/tenantcheck/ProcessInstanceRestServiceTenantCheckTest.java
=> chore(fork): Rename Groups.CAMUNDA_ADMIN to Groups.OPERATON_ADMIN

pom.xml, spring-boot-starter/starter-qa/integration-test-liquibase/pom.xml, spring-boot-starter/starter-qa/integration-test-liquibase/src/test/java/org/operaton/bpm/springboot/project/qa/liquibase/LiquibaseApplicationIT.java, spring-boot-starter/starter-qa/integration-test-plugins/pom.xml, spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-all/pom.xml, spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-all/src/test/java/org/operaton/bpm/springboot/project/qa/spin/SpinApplicationTestIT.java, spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-json-jackson/pom.xml, spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-json-jackson/src/test/java/org/operaton/bpm/springboot/project/qa/spin/SpinApplicationTestIT.java, spring-boot-starter/starter-qa/integration-test-request-scope/pom.xml, spring-boot-starter/starter-qa/integration-test-request-scope/src/test/java/org/operaton/bpm/springboot/project/qa/simple/RequestScopeIT.java, spring-boot-starter/starter-qa/integration-test-simple/pom.xml, spring-boot-starter/starter-qa/integration-test-simple/src/test/java/org/operaton/bpm/springboot/project/qa/simple/SimpleApplicationIT.java, spring-boot-starter/starter-qa/pom.xml
Modules
- spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-all
- spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-json-jackson
- spring-boot-starter/starter-qa/integration-test-request-scope
spring-boot-starter/starter-qa/integration-test-simple
- spring-boot-starter/starter-qa/integration-test-liquibase
- ./root.xml: Activate recipe org.openrewrite.java.testing.cleanup.TestsShouldNotBePublic
related to #27
=> refactor(tests): JUnit5 migration - spring-boot-starter

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-instance.ftl, engine/src/main/java/org/operaton/bpm/engine/history/HistoricProcessInstanceQuery.java, engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml, engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceTest.java
related to camunda/camunda-bpm-platform#4757
Backported commit fab81850706 from the camunda-bpm-platform repository.
=> fix(engine): allow querying for hist pis by async activities (#4769)

pom.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4530
Backported commit e22fc83ef40 from the camunda-bpm-platform repository.
=> chore(dmn): bump feel scala version to 1.18.1

webapps/frontend/ui/admin/client/scripts/pages/execution-metrics.js
related to camunda/camunda-bpm-platform#4743
Backported commit 4d17b903474 from the camunda-bpm-platform repository.
=> fix(admin): fix display of usage metrics > 12 months (#4778)

TESTING.md
=> chore(docs): Update TESTING.md for JUnit 5

spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/XmlTestUtil.java, spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/dom/XmlDomMapJavaToXmlScriptTest.java, spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/dom/XmlDomMapJavaToXmlTest.java
related to: https://github.com/camunda/camunda-bpm-platform/issues/4606
Backported commit f918bf020dc from the camunda-bpm-platform repository.
Original author: prajwolbhandari1 <147008971+prajwolbhandari1@users.noreply.github.com>
=> test(spin): exclude time zone from unit tests as it is hard coded

qa/integration-tests-webapps/shared-engine/pom.xml
related to: operaton/operaton#226 operaton/operaton#186
=> fix(install): skip operaton-qa-integration-tests-webapps-shared-engine for install goal (#226)

spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/format/JacksonJsonDataFormat.java, spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/format/TypeHelper.java
=> Fix instanceof check and cast with pattern matching in spin/dataformat-json-jackson. (#85)

clients/java/client/pom.xml
=> fix(build): Import operaton-commons-bom

.github/scripts/prepare-distros-archive.sh, .github/scripts/prepare-reports.sh, .github/workflows/build.yml, .github/workflows/nighly-build.yml, .gitignore, pom.xml
- Fixed error in Generate Reports: Comment in Maven command line broke the job
- Upgrade actions
- added buildplan-maven-plugin
- added sloc-maven-plugin
related to #201
=> Fix nightly build

.github/jreleaser/changelog.tpl, .github/workflows/release.yml, jreleaser.yml
Provide a `release` workflow and `jrelease.yaml` for automatic release builds.
relates to #37
=> feat(build): Set up release workflow (#37)

qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/variables/DeserializableVariableTest.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/beans/TimerExpressionBean.java, qa/performance-tests-engine/src/main/java/org/operaton/bpm/qa/performance/engine/framework/PerfTestBuilder.java, qa/performance-tests-engine/src/main/java/org/operaton/bpm/qa/performance/engine/framework/PerfTestRunner.java, qa/performance-tests-engine/src/main/java/org/operaton/bpm/qa/performance/engine/framework/report/SectionedHtmlReportBuilder.java, qa/performance-tests-engine/src/main/java/org/operaton/bpm/qa/performance/engine/junit/AuthHelper.java, qa/performance-tests-engine/src/main/java/org/operaton/bpm/qa/performance/engine/junit/PerfTestProcessEngine.java
=> chore(sonar): Fix instanceof check and cast with pattern matching in qa

engine-rest/docs/package.json, webapps/frontend/package.json
The webapps have their own versioning, this should match the project's overall version. Should be merged before beta-2 release.
=> chore(webapps): adjusted version of the webapps to be 1.0.0-beta-2

clients/java/client/src/main/java/org/operaton/bpm/client/impl/ExternalTaskClientLogger.java, clients/java/client/src/main/java/org/operaton/bpm/client/topic/impl/TopicSubscriptionManager.java, clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/mapper/FileValueMapper.java
=> Fix instanceof check and cast with pattern matching in clients. (#85)

README.md
Adds a Slack badge to README and changes the formatting. The Slack button leads to the invitation link.
=> feat(README): Add Slack badge

README.md
Added "Contributors" section as described by https://allcontributors.org/docs/en/bot/installation#3-create-a-readmemd
related to #254
=> Add AllContributors

model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/builder/AbstractFlowNodeBuilder.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/impl/instance/FlowNodeImpl.java, model-api/dmn-model/src/test/java/org/operaton/bpm/model/dmn/DmnModelTest.java, model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/impl/instance/DomElementImpl.java, model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/impl/instance/ModelElementInstanceImpl.java, model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/impl/type/child/ChildElementCollectionImpl.java, model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/impl/type/reference/ElementReferenceCollectionImpl.java, model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/impl/util/ModelUtil.java, model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/type/reference/AttributeReferenceCollection.java, model-api/xml-model/src/test/java/org/operaton/bpm/model/xml/validation/TestResultFormatter.java
=>  Fix instanceof check and cast with pattern matching in operaton-model-apis

distro/run/assembly/pom.xml, distro/run/core/pom.xml, distro/run/distro/pom.xml, distro/run/modules/example/pom.xml, distro/run/modules/pom.xml, distro/run/modules/rest/pom.xml, distro/run/modules/webapps/pom.xml, distro/run/pom.xml, distro/run/qa/example-plugin/pom.xml, distro/run/qa/integration-tests/pom.xml, distro/run/qa/pom.xml, distro/run/qa/runtime/pom.xml
Some modules have not been updated properly.
fixes #287
=> core(build): Bump remaining modules to 1.0.0-beta-2

parent/pom.xml
Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4751
Backported commit d69bbf8f562 from the camunda-bpm-platform repository.
=> chore(parent): Set Spring Version to 6.1.15

engine-rest/engine-rest-openapi/README.md, engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/{id}/errorDetails/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/external-task-log/{id}/error-details/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/history/job-log/{id}/stacktrace/get.ftl, engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/stacktrace/get.ftl
related to camunda/camunda-bpm-platform#3298
Backported commit 7cec7e1 from the camunda-bpm-platform repository.
Original author: PHWaechtler <helene.waechtler@camunda.com>
=> fix(openApi): add missing schema declarations

.github/scripts/set-project-version.sh, distro/license-book/src/main/resources/license-book.txt
Private the scipt `set-project-version.sh`. This reads the current version from the root pom.xml and takes the version to set as argument.
It changes all versions and checks afterwards that no match is left.
=> Add script to update the version in all project files

juel/src/main/java/org/operaton/bpm/impl/juel/NumberOperations.java, juel/src/main/java/org/operaton/bpm/impl/juel/Scanner.java, juel/src/main/java/org/operaton/bpm/impl/juel/TypeConverterImpl.java
- Introduces comma-separated labels in switch cases
- instanceof checks and casts are replaced with instanceof with assign to a binding variable
- Code simplifications
related to #85
=> refactor(juel): Incorporate new language features

engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/exception/ExceptionHandlerHelper.java
related to camunda/camunda-bpm-platform#4824
Backported commit 091ec0221e from the camunda-bpm-platform repository.
Original author: Hao <kyrieeeee2@gmail.com>
=> refactor(engine-rest): ensure proper exception code assignment in ExceptionHandlerHelper (#4600)

distro/operaton-welcome/index.html
=> chore(webapp): Remove Enterprise Support Button [#273]

.github/workflows/build.yml, engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/impl/FetchAndLockRestServiceInteractionTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/history/UserOperationLogAuthorizationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoryCleanupTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceGetTelemetryDataTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/metrics/MetricsDisabledTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/async/AsyncTaskTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/conditional/MixedConditionalEventTest.java, engine/src/test/java/org/operaton/bpm/engine/test/cmmn/listener/VariableListenerTest.java, engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingForkTest.java, engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingMessageCorrelationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/standalone/testing/ProcessEngineRuleParameterizedJunit4Test.java, webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/ProcessInstanceRestServiceTest.java
=> qa: enable tests, which don't fail anymore (#246)

.github/workflows/nighly-build.yml, pom.xml
Include distro in nightly build
fixes #314
=> fix(build): Enable `run` in `distros` profile & build nightly

qa/large-data-tests/src/test/java/org/operaton/bpm/qa/largedata/optimize/OptimizeApiPageSizeTest.java
Method optimizeServiceFunctions must be static
closes #372
=> fix(tests): Fix OptimizeApiPageSizeTest

engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/BpmnBehaviorLogger.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/helper/BpmnExceptionHandler.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/behavior/BpmnBehaviorLoggerTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/tasklistener/TaskListenerErrorThrowTest.java, engine/src/test/resources/org/operaton/bpm/engine/test/bpmn/behavior/BpmnBehaviorLoggerTest.UnhandledBpmnError.bpmn20.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4667
Signed-off-by: Sowmya HL <Sowmya.HL@fmr.com>
Backported commit 7fd1db10c7 from the camunda-bpm-platform repository.
Original author: Sowmya HL <Sowmya.HL@fmr.com>
=> feat(engine): include error message of unhandled BPMN error in log

distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/Element.java, distro/wildfly26/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/Element.java, engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/ProcessInstanceRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/util/JsonPathUtil.java, engine-spring/core/src/main/java/org/operaton/bpm/engine/spring/components/registry/ActivitiStateHandlerRegistry.java, engine/src/main/java/org/operaton/bpm/engine/impl/HistoricProcessInstanceReportImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/SchemaOperationsProcessEngineBuild.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmd/DeleteJobsCmd.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetNextIdBlockCmd.java, engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupJobDeclaration.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/deploy/cache/CacheDeployer.java, engine/src/main/java/org/operaton/bpm/engine/impl/scripting/engine/JuelScriptEngine.java, engine/src/test/java/org/operaton/bpm/engine/test/api/repository/diagram/ProcessDiagramRetrievalTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/async/RetryCmdDeployment.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/usertask/UserTaskTestCreateTaskListener.java, model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/OperatonExtensionsTest.java, model-api/dmn-model/src/test/java/org/operaton/bpm/model/dmn/ExampleCompatibilityTest.java, model-api/dmn-model/src/test/java/org/operaton/bpm/model/dmn/OperatonExtensionsTest.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/cdi/JobExecutorRequestContextTest.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/delegation/DelegatedVariableMappingTest.java, spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/mapping/Order.java, test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/deployment/ProcessEngineExtensionDeploymentIdAccess.java
Removes unused private fields, methods and inner types.
related to #88
=> chore: Remove unused private members

test-utils/testcontainers/pom.xml, test-utils/testcontainers/src/test/java/org/operaton/impl/test/utils/testcontainers/DatabaseContainerProviderTest.java
=> refactor(tests): JUnit 5 migration of module test-utils/testcontainers

model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/builder/AbstractCallActivityBuilder.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/builder/AbstractStartEventBuilder.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/builder/AbstractSubProcessBuilder.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/builder/AbstractTaskBuilder.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/impl/instance/CallActivityImpl.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/impl/instance/ParallelGatewayImpl.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/impl/instance/StartEventImpl.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/impl/instance/SubProcessImpl.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/impl/instance/TaskImpl.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/instance/CallActivity.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/instance/ParallelGateway.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/instance/StartEvent.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/instance/SubProcess.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/instance/Task.java, model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/OperatonExtensionsTest.java
=> chore: Mark methods operatonAsync for removal & resolve usages

engine/src/main/java/org/operaton/bpm/engine/impl/cfg/ConfigurationLogger.java, engine/src/main/java/org/operaton/bpm/engine/impl/db/EnginePersistenceLogger.java
- changes multiline strings to text blocks
related to #85
=> refactor(engine): changes multiline strings to text blocks

webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/db/QuerySessionFactory.java
- changes multiline strings to text blocks
related to #85
=> refactor(webapps): changes multiline strings to text blocks

parent/pom.xml
The code coverage should work now again.
=> reenable code coverage (#230)

distro/run/core/src/main/java/org/operaton/bpm/run/property/OperatonBpmRunProcessEnginePluginProperty.java, engine/src/main/java/org/operaton/bpm/engine/impl/db/HasDbReferences.java, engine/src/main/java/org/operaton/bpm/engine/impl/db/entitymanager/DbEntityManager.java, engine/src/main/java/org/operaton/bpm/engine/impl/el/StartProcessVariableScope.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricCaseInstanceManager.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricProcessInstanceManager.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricTaskInstanceManager.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/JobEntity.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/TaskEntity.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/rest/RestIT.java, spin/core/src/main/java/org/operaton/spin/DataFormats.java
Replace by
- Collections.emptyList()
- Collections.emptySet()
- Collections.emptyMap()
Resolve Sonar findings of type: java:S1596
=> chore: Replace Collections#EMPTY_[LIST|SET|MAP]

commons/utils/src/test/java/org/operaton/commons/utils/IoUtilTest.java, engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricJobLogTest.java, engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/logging/ProcessDataLoggingContextTest.java, engine/src/test/java/org/operaton/bpm/engine/test/standalone/db/SchemaLogUpgradeScriptPatternTest.java, engine/src/test/java/org/operaton/bpm/engine/test/standalone/variables/FileValueSerializerTest.java, model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/ResourceRolesTest.java, model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/validation/ValidateProcessTest.java, model-api/xml-model/src/test/java/org/operaton/bpm/model/xml/StringUtilTest.java, model-api/xml-model/src/test/java/org/operaton/bpm/model/xml/instance/ModelElementInstanceTest.java, model-api/xml-model/src/test/java/org/operaton/bpm/model/xml/type/child/ChildElementCollectionTest.java, model-api/xml-model/src/test/java/org/operaton/bpm/model/xml/type/reference/ReferenceTest.java, quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/config/OperatonEngineConfigurationConfigTest.java, quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/config/OperatonEngineJobExecutorConfigTest.java, spin/dataformat-json-jackson/src/test/java/org/operaton/spin/json/tree/JsonTreeEditListPropertyScriptTest.java, spin/dataformat-json-jackson/src/test/java/org/operaton/spin/json/tree/JsonTreeEditListPropertyTest.java, spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/dom/XmlDomXPathScriptTest.java, spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/dom/XmlDomXPathTest.java, spring-boot-starter/starter/src/test/java/org/operaton/bpm/spring/boot/starter/jdbc/HistoryLevelDeterminatorJdbcTemplateImplTest.java
Resolve Sonar findings of type: java:S5838
related to #27
=> refactor(tests): Simplify chained AssertJ assertions to dedicated assertion

clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/format/xml/DomXmlDataFormat.java, commons/logging/src/main/java/org/operaton/commons/logging/BaseLogger.java, distro/wildfly26/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/service/MscExecutorService.java, engine-plugins/spin-plugin/src/test/java/org/operaton/spin/plugin/variables/TypedValueAssert.java, engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/converter/JacksonAwareStringToTypeConverter.java, engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/converter/PeriodUnitConverter.java, engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/task/impl/TaskResourceImpl.java, engine/src/main/java/org/operaton/bpm/container/impl/deployment/PostDeployInvocationStep.java, engine/src/main/java/org/operaton/bpm/container/impl/deployment/PreUndeployInvocationStep.java, engine/src/main/java/org/operaton/bpm/engine/impl/RepositoryServiceImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/CaseExecutionCommandBuilderImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/handler/SentryHandler.java, engine/src/test/java/org/operaton/bpm/engine/test/util/TypedValueAssert.java, model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/test/AbstractModelElementInstanceTest.java, spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/format/JacksonJsonDataFormatReader.java, spin/dataformat-xml-dom/src/main/java/org/operaton/spin/impl/xml/dom/format/DomXmlDataFormatReader.java
Applied OpenRewrite recipe org.openrewrite.staticanalysis.CombineSemanticallyEqualCatchBlocks
Resolve Sonar findings of type: java:S2147
related to #88
=> refactor: Combine semantically equal catch blocks

engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/MigrationRestServiceInteractionTest.java, engine/src/test/java/org/operaton/bpm/engine/impl/incident/CompositeIncidentHandlerTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/GroupAuthorizationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/cfg/AuthorizationCheckRevokesCfgTest.java
Resolve Sonar findings of type: java:S6068
related to #88
=> refactor(tests): Remove unnecessary usage of Mockito.eq()

commons/logging/src/main/java/org/operaton/commons/logging/BaseLogger.java, engine-dmn/feel-scala/src/main/java/org/operaton/bpm/dmn/feel/impl/scala/spin/SpinValueMapperFactory.java, engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/AbstractSearchQueryDto.java, engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/security/auth/ProcessEngineAuthenticationFilter.java, engine/src/main/java/org/operaton/bpm/container/impl/deployment/jobexecutor/StartJobAcquisitionStep.java, engine/src/main/java/org/operaton/bpm/engine/impl/DefaultArtifactFactory.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java, engine/src/main/java/org/operaton/bpm/engine/impl/form/validator/FormValidators.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/GenericManagerFactory.java, engine/src/main/java/org/operaton/bpm/engine/impl/util/ReflectUtil.java, webapps/assembly/src/main/java/org/operaton/bpm/cockpit/rest/dto/AbstractRestQueryParametersDto.java, webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/security/auth/ContainerBasedAuthenticationFilter.java, webapps/assembly/src/main/java/org/operaton/bpm/webapp/rest/dto/AbstractRestQueryParametersDto.java
Replace Class#newInstance() by Class#getDeclaredConstructor().newInstance()
Catch additional exceptions and collapse exceptions catches with equal body.
=> refactor: Resolve deprecation of Class#newInstance

distro/run/qa/integration-tests/src/test/java/org/operaton/bpm/run/qa/webapps/LoginIT.java, engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/task/CdiTaskServiceTest.java, engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/UserRestServiceInteractionTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/cfg/DeploymentCacheCfgTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/form/FormServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoricDecisionInstanceStatisticsQueryTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/variables/JavaSerializationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/variables/scope/TargetVariableScopeTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/common/AbstractProcessEngineServicesAccessTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/gateway/ExclusiveGatewayTest.java, engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingVariableFetchingAndDeletionTest.java, engine/src/test/java/org/operaton/bpm/engine/test/standalone/interceptor/MultiEngineCommandContextTest.java, model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/BpmnDiTest.java, model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/CreateModelTest.java, model-api/cmmn-model/src/test/java/org/operaton/bpm/model/cmmn/CreateModelTest.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/spring/timer/SpringServletPATimerStartEventExpressionTest.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/LoginIT.java, test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/deployment/EnsureDbCleanTest.java
Test methods that did not have any assertion have been extended by an assertion.
Resolves Sonar findings of type: java:S2699 "Tests should include assertions"
related to #88
=> refactor(tests): Add assertions to test case

engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/ParseExceptionDto.java, engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/DeploymentRestServiceInteractionTest.java, engine/src/main/java/org/operaton/bpm/engine/ParseException.java, engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/async/AsyncAfterTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/callactivity/CallActivityTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/compensate/CompensationEventParseInvalidProcessTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/conditional/ConditionalStartEventTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/error/BoundaryErrorEventTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/escalation/EscalationEventParseInvalidProcessTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/link/LinkEventTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/message/MessageBoundaryEventTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/message/MessageIntermediateEventTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/message/MessageStartEventTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/signal/SignalEventParseInvalidProcessTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/external/ExternalTaskParseTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/gateway/EventBasedGatewayTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/gateway/ExclusiveGatewayTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/iomapping/InputOutputEventTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/iomapping/InputOutputTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/job/JobPrioritizationBpmnConstantValueTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/subprocess/transaction/TransactionSubProcessTest.java, engine/src/test/java/org/operaton/bpm/engine/test/dmn/businessruletask/DmnBusinessRuleTaskResultMappingTest.java
Replace by getResourceReports()
=> refactor: Resolve deprecation usage ParseException#getResorceReports

engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/event/AbstractCdiEventListener.java, engine-rest/engine-rest-openapi-generator/src/main/java/org/operaton/bpm/engine/rest/openapi/generator/impl/TemplateParser.java
=> refactor: Resolve usage of deprecated API

.github/workflows/release-publish.yml
Add workflow that triggers the operaton-docker.
related to operaton/operaton-docker#2
=> build: Trigger docker image build on release

.github/workflows/release-publish.yml
Fix the syntax issues on the workflow and evaluate response
=> build: Fix release-publish.yml

engine-plugins/spin-plugin/src/test/java/org/operaton/spin/plugin/variables/HistoricVariableJsonSerializationTest.java, engine-plugins/spin-plugin/src/test/java/org/operaton/spin/plugin/variables/JavaSerializationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceAuthorizationsTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java, engine/src/test/java/org/operaton/bpm/engine/test/standalone/variables/FileValueSerializerTest.java, javaee/jobexecutor-ra/src/main/java/org/operaton/bpm/container/impl/threading/ra/inflow/JobExecutionHandlerActivation.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/PaDataFormatConfiguratorJodaTest.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/PaDataFormatConfiguratorTest.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/rest/RestIT.java, webapps/assembly/src/test/java/org/operaton/bpm/webapp/plugin/resource/AbstractAppPluginRootResourceTest.java
=> chore: Remove unnecessary throws declarations

distro/run/core/src/main/java/org/operaton/bpm/run/OperatonBpmRunDeploymentConfiguration.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/scripttask/ScriptTaskTest.java
Converting string concatenations in tests to text blocks.
=> Fix some SonarQube findings

clients/java/client/src/it/java/org/operaton/bpm/client/util/TestUtil.java, engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/CdiProcessEngineTestCase.java, engine-plugins/spin-plugin/src/main/java/org/operaton/spin/plugin/impl/feel/integration/SpinValueMapper.java, engine/src/main/java/org/operaton/bpm/engine/impl/TaskQueryImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ShellActivityBehavior.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/diagram/ProcessDiagramLayoutFactory.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java, engine/src/main/java/org/operaton/bpm/engine/impl/metrics/parser/MetricsExecutionListener.java, engine/src/main/java/org/operaton/bpm/engine/impl/test/AbstractProcessEngineTestCase.java, engine/src/main/java/org/operaton/bpm/engine/impl/variable/serializer/BooleanValueSerializer.java, engine/src/test/java/org/operaton/bpm/engine/test/api/context/ProcessEngineContextTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/SendMessageDelegate.java, engine/src/test/java/org/operaton/bpm/engine/test/util/ExecutionTree.java, engine/src/test/java/org/operaton/bpm/engine/test/util/ProcessEngineTestRule.java, javaee/jobexecutor-ra/src/main/java/org/operaton/bpm/container/impl/threading/ra/JcaExecutorServiceConnector.java, juel/src/main/java/org/operaton/bpm/impl/juel/AstChoice.java, juel/src/main/java/org/operaton/bpm/impl/juel/AstUnary.java, spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/JacksonJsonNode.java, spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/query/JacksonJsonPathQuery.java, spin/dataformat-json-jackson/src/test/java/org/operaton/spin/json/tree/JsonTreeSetPropertyTest.java, spring-boot-starter/starter-client/spring-boot/src/main/java/org/operaton/bpm/client/spring/boot/starter/impl/PropertiesAwareClientFactory.java, spring-boot-starter/starter-client/spring/src/main/java/org/operaton/bpm/client/spring/impl/client/ClientFactory.java, spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/SpringBootProcessApplication.java, spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/configuration/impl/DefaultProcessEngineConfiguration.java, spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/event/EventPublisherPlugin.java, spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/event/PublishDelegateParseListener.java, webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/test/util/JobExecutorHelper.java
Performed OpenRewrite recipe org.openrewrite.staticanalysis.AvoidBoxedBooleanExpressions
related to #88
=> chore: Avoid using boxed "Boolean" types directly in boolean expressions

clients/java/client/src/it/java/org/operaton/bpm/client/util/TestUtil.java, engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/CdiProcessEngineTestCase.java, engine-plugins/spin-plugin/src/main/java/org/operaton/spin/plugin/impl/feel/integration/SpinValueMapper.java, engine/src/main/java/org/operaton/bpm/engine/impl/TaskQueryImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ShellActivityBehavior.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/diagram/ProcessDiagramLayoutFactory.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java, engine/src/main/java/org/operaton/bpm/engine/impl/metrics/parser/MetricsExecutionListener.java, engine/src/main/java/org/operaton/bpm/engine/impl/test/AbstractProcessEngineTestCase.java, engine/src/main/java/org/operaton/bpm/engine/impl/variable/serializer/BooleanValueSerializer.java, engine/src/test/java/org/operaton/bpm/engine/test/api/context/ProcessEngineContextTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/SendMessageDelegate.java, engine/src/test/java/org/operaton/bpm/engine/test/util/ExecutionTree.java, engine/src/test/java/org/operaton/bpm/engine/test/util/ProcessEngineTestRule.java, javaee/jobexecutor-ra/src/main/java/org/operaton/bpm/container/impl/threading/ra/JcaExecutorServiceConnector.java, juel/src/main/java/org/operaton/bpm/impl/juel/AstChoice.java, juel/src/main/java/org/operaton/bpm/impl/juel/AstUnary.java, spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/JacksonJsonNode.java, spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/query/JacksonJsonPathQuery.java, spin/dataformat-json-jackson/src/test/java/org/operaton/spin/json/tree/JsonTreeSetPropertyTest.java, spring-boot-starter/starter-client/spring-boot/src/main/java/org/operaton/bpm/client/spring/boot/starter/impl/PropertiesAwareClientFactory.java, spring-boot-starter/starter-client/spring/src/main/java/org/operaton/bpm/client/spring/impl/client/ClientFactory.java, spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/SpringBootProcessApplication.java, spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/configuration/impl/DefaultProcessEngineConfiguration.java, spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/event/EventPublisherPlugin.java, spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/event/PublishDelegateParseListener.java, webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/test/util/JobExecutorHelper.java
This reverts commit 9504f4e9ca9489d5676d3ac05bd91af2a26b6039.
=> chore: Revert "chore: Avoid using boxed "Boolean" types directly in boolean expressions (#452)

spring-boot-starter/starter-security/pom.xml, spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/SampleApplication.java, spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/AbstractSpringSecurityIT.java, spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OperatonBpmSampleApplicationIT.java, spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OperatonBpmSecurityAutoConfigOauth2ApplicationIT.java, spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/OAuth2GrantedAuthoritiesMapperIT.java, spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/OperatonIdentityProviderIT.java, spring-boot-starter/starter-security/src/test/resources/oauth2-mock.properties
related to https://github.com/camunda/camunda-bpm-platform/issues/4453
Backported commit 2d02d61410 from the camunda-bpm-platform repository.
=> tests(starter): add tests for oauth2 and identity  (fixes #175)

commons/logging/src/test/java/org/operaton/commons/logging/ExampleLogger.java, connect/core/src/main/java/org/operaton/connect/Connectors.java, connect/core/src/main/java/org/operaton/connect/impl/ConnectLogger.java, connect/http-client/src/main/java/org/operaton/connect/httpclient/impl/AbstractHttpConnector.java, connect/http-client/src/main/java/org/operaton/connect/httpclient/impl/HttpLogger.java, connect/http-client/src/main/java/org/operaton/connect/httpclient/impl/util/ParseUtil.java, connect/soap-http-client/src/main/java/org/operaton/connect/httpclient/soap/impl/SoapHttpLogger.java, engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/DmnLogger.java, engine-dmn/feel-juel/src/main/java/org/operaton/bpm/dmn/feel/impl/juel/FeelLogger.java, engine-spring/core/src/main/java/org/operaton/bpm/engine/spring/SpringBeansResolverFactory.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/BpmnActivityBehavior.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ExclusiveGatewayActivityBehavior.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/InclusiveGatewayActivityBehavior.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/deployer/BpmnDeployer.java
Logger fields that are named upper case have been made final.
Resolve Sonar findings of type: java:S3008
related to #88
=> refactor: Make logger instances final

model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/impl/instance/ModelElementInstanceImpl.java, model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/impl/instance/ModelTypeInstanceContext.java
Refactore class to record (with correct "final" and removed getters).
=> Record class refactoring

parent/pom.xml
https://github.com/operaton/operaton/issues/60
=> Configure maven build to use only one thread for test execution

commons/logging/src/main/java/org/operaton/commons/logging/BaseLogger.java, commons/logging/src/test/java/org/operaton/commons/logging/BaseLoggerTest.java
also: add isTraceEnabled() for completeness and use is<Level>Enabled() methods to avoid having unused methods in the code (isWarnEnabled & isErrorEnabled were not used).
=> security: Sanitize message parameters to avoid injection attacks

engine/src/main/java/org/operaton/bpm/container/impl/jmx/MBeanServiceContainer.java
https://sonarcloud.io/project/issues?fileUuids=AZLaQmoy8ZwKcH34-TO3&issueStatuses=OPEN%2CCONFIRMED&id=operaton_operaton
=> chore: resolve issues reported by SonarQube

engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/el/DefaultScriptEngineResolver.java, engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/hal/HalLinker.java, engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/runtime/impl/FilterResourceImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/ActivityExecutionTreeMapping.java, engine/src/main/java/org/operaton/bpm/engine/impl/batch/BatchElementConfiguration.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java, engine/src/main/java/org/operaton/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/cfg/standalone/StandaloneTransactionContext.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetActivityInstanceCmd.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/entity/runtime/CaseExecutionEntity.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/execution/CaseExecutionImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/model/CmmnSentryDeclaration.java, engine/src/main/java/org/operaton/bpm/engine/impl/core/model/CoreModelElement.java, engine/src/main/java/org/operaton/bpm/engine/impl/db/entitymanager/cache/DbEntityCache.java, engine/src/main/java/org/operaton/bpm/engine/impl/db/sql/DbSqlSessionFactory.java, engine/src/main/java/org/operaton/bpm/engine/impl/interceptor/CommandContext.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/DeploymentEntity.java, engine/src/main/java/org/operaton/bpm/engine/impl/pvm/process/ProcessDefinitionImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/scripting/env/ScriptingEnvironment.java, engine/src/main/java/org/operaton/bpm/engine/impl/test/TestHelper.java, engine/src/main/java/org/operaton/bpm/engine/impl/util/ClassNameUtil.java, engine/src/main/java/org/operaton/bpm/engine/impl/util/CollectionUtil.java, model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/impl/ModelImpl.java, model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/impl/validation/ValidationResultsCollectorImpl.java, webapps/assembly/src/main/java/org/operaton/bpm/admin/impl/DefaultAdminRuntimeDelegate.java, webapps/assembly/src/main/java/org/operaton/bpm/cockpit/impl/DefaultCockpitRuntimeDelegate.java
Resolve Sonar findings of type: java:S3824
related to #88
=> refactor: Replace this "Map.get()" and condition with a call to "Map.computeIfAbsent()"

distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/BpmPlatformParser1_1.java, distro/wildfly26/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/BpmPlatformParser1_1.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java, engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java, engine/src/main/java/org/operaton/bpm/engine/repository/ProcessApplicationDeploymentBuilder.java
https://sonarcloud.io/project/issues?fileUuids=AZLaQmot8ZwKcH34-S4N&issueStatuses=OPEN%2CCONFIRMED&id=operaton_operaton
=> chore: improves findings reported by SonarQube

engine/src/test/java/org/operaton/bpm/application/impl/deployment/RedeploymentProcessApplicationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/form/RetrieveOperatonFormRefTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/history/BulkHistoryDeleteTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoricDecisionInstanceStatisticsQueryTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoryCleanupTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoryServiceAsyncOperationsTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/batch/BatchSetRemovalTimeTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceTenantTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/JobQueryTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceAsyncOperationsTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/SuspendJobDefinitionTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/metrics/MetricsIntervalTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/MultiTenancyMessageCorrelationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ExecutionQueryTest.java, engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricActivityInstanceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/standalone/interceptor/CommandContextInterceptorTest.java
Resolve Sonar warnings of type java:S5845 - Assertions comparing incompatible types should not be made
related to #88
=> refactor: Extract method calls in try-blocks within tests to variables 

internal-dependencies/pom.xml, parent/pom.xml, test-utils/assert/core/pom.xml, test-utils/assert/qa/pom.xml, test-utils/testcontainers/pom.xml, webapps/assembly/pom.xml
- Upgrade slf4j 1.7.26 -> 2.0.16
- Upgrade logback-classic 1.2.11 -> 1.5.16
=> dependencies: Upgrade slf4j and logback

clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/format/serializable/SerializableDataFormat.java, clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/format/xml/DomXmlDataFormat.java, commons/utils/src/main/java/org/operaton/commons/utils/IoUtil.java, engine-plugins/identity-ldap/src/test/java/org/operaton/bpm/identity/ldap/util/LdapTestEnvironment.java, engine/src/main/java/org/operaton/bpm/engine/impl/ant/DeployBarTask.java, engine/src/main/java/org/operaton/bpm/engine/impl/ant/LaunchThread.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ShellActivityBehavior.java, engine/src/main/java/org/operaton/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/db/sql/DbSqlSession.java, engine/src/main/java/org/operaton/bpm/engine/impl/util/IoUtil.java, engine/src/main/java/org/operaton/bpm/engine/impl/variable/serializer/JavaObjectSerializer.java, engine/src/test/java/org/operaton/bpm/engine/test/api/variables/JavaSerializationTest.java, juel/src/main/java/org/operaton/bpm/impl/juel/ExpressionFactoryImpl.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/Bpmn.java, model-api/cmmn-model/src/main/java/org/operaton/bpm/model/cmmn/Cmmn.java, model-api/dmn-model/src/main/java/org/operaton/bpm/model/dmn/Dmn.java, model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/impl/util/IoUtil.java, spin/core/src/main/java/org/operaton/spin/impl/util/SpinIoUtil.java, spring-boot-starter/starter-webapp-core/src/main/java/org/operaton/bpm/spring/boot/starter/webapp/filter/ResourceLoadingProcessEnginesFilter.java, webapps/assembly/src/test/java/org/operaton/bpm/webapp/impl/security/filter/SecurityFilterRulesTest.java
Resolves:
https://sonarcloud.io/project/issues?impactSoftwareQualities=MAINTAINABILITY&rules=java%3AS2093&issueStatuses=OPEN%2CCONFIRMED&id=operaton_operaton
=> chore: use try-with-resources

engine-spring/core/src/main/java/org/operaton/bpm/engine/spring/components/jobexecutor/SpringJobExecutor.java, engine/src/main/java/org/operaton/bpm/container/impl/jmx/services/JmxManagedThreadPool.java, engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/JobExecutor.java, engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/JobExecutorLogger.java, engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/RuntimeContainerJobExecutor.java, engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/SequentialJobAcquisitionRunnable.java, engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/ThreadPoolJobExecutor.java, engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/DelayDelegate.java, engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobAcquisitionLoggingTest.java, engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutionLoggingTest.java, engine/src/test/resources/org/operaton/bpm/engine/test/jobexecutor/SimpleAsyncDelayProcess.bpmn20.xml
* add test cases for the job-acquisition and job-execution logs
related https://github.com/camunda/camunda-bpm-platform/issues/2666
Backported commit 824b35f3f2 from the camunda-bpm-platform repository.
Original author: Palanisamy, Prakash <prakash.palanisamy@fmr.com>
=> chore(engine): add debug logs to improve job acquisition job execution logging

engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/TaskVariableLocalRestResourceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/TaskVariableRestResourceInteractionTest.java, engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/UserOperationLogRestServiceQueryTest.java, engine/src/main/java/org/operaton/bpm/engine/impl/db/sql/DbSqlSession.java, engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/history/HistoricExternalTaskLogAuthorizationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceCaseInstanceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceCaseTaskTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyStartTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/TenantIdProviderTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/optimize/GetRunningHistoricProcessInstancesForOptimizeTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/message/MessageCorrelationUserOperationLogTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/SetProcessDefinitionVersionCmdTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskQueryTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskVariablesTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/signal/SignalEventPayloadTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/receivetask/ReceiveTaskTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/subprocess/transaction/TransactionSubProcessTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/tasklistener/TaskListenerTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/usertask/UserTaskTest.java, engine/src/test/java/org/operaton/bpm/engine/test/cmmn/cmmn10/Cmmn10CompatibilityTest.java, engine/src/test/java/org/operaton/bpm/engine/test/cmmn/operation/CaseExecutionCompletionTest.java, engine/src/test/java/org/operaton/bpm/engine/test/cmmn/processtask/ProcessTaskTest.java, engine/src/test/java/org/operaton/bpm/engine/test/cmmn/repetition/RepetitionRuleTest.java, engine/src/test/java/org/operaton/bpm/engine/test/cmmn/stage/AutoCompleteTest.java, test-utils/assert/core/src/test/java/org/operaton/bpm/engine/test/assertions/bpmn/ProcessInstanceAssertIsWaitingForTest.java
cleanups:
- make fields static
- remove explicit type arguments where not needed
related to #88
=> refactor: Remove unused local variables & cleanup

pom.xml, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/jodatime/JodaTimeClassloadingTest.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/slf4j/Slf4jClassloadingTest.java, qa/tomcat-runtime/pom.xml, qa/tomcat-runtime/src/main/conf/server.xml
- add missing libraries to tomcat-runtime
- delete unused webapp deployments for Tomcat to speed up test execution
- fix JNDI test issue
fixes#522
=> fix: Fix engine integration tests for Tomcat

webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/db/QuerySessionFactory.java, webapps/assembly/src/test/java/org/operaton/bpm/webapp/impl/db/QuerySessionFactoryTest.java, webapps/assembly/src/test/resources/operaton-skip-check.cfg.xml
Related to https://github.com/camunda/camunda-bpm-platform/issues/4867
Backported commit 50989d89fa from the camunda-bpm-platform repository.
=> fix(webapps): add skipIsolationLevelCheck to configuration on webapp init

engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/UserRestServiceInteractionTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/IncidentAuthorizationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/repository/RepositoryServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/RuntimeServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/error/BoundaryErrorEventTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/signal/SignalEventReceivedBuilderTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/gateway/InclusiveGatewayTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/property/PropertyTest.java, engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceDurationReportTest.java, engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorPriorityRangeConfigurationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/standalone/entity/JobEntityTest.java, freemarker-template-engine/pom.xml, freemarker-template-engine/src/test/java/org/operaton/templateengines/engine/FreeMarkerScriptEngineTest.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/transactions/AsyncJobExecutionTest.java
=> chore: add assertions to tests

bom/pom.xml, pom.xml
And remove the module from root pom.xml as "bom" is included as a module.
related to #533
=> refactor(build): Add internal-dependencies as module to bom/pom.xml

pom.xml
=> fix(build): Remove junit5-extension-dmn from root pom.xml

distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/deployment/processor/ProcessApplicationProcessor.java, qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7210/jobexecutor/ExclusiveOverProcessHierarchiesTest.java
Resolves findings: https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&tags=java14%2Cjava15%2Cjava16%2Cjava17&id=operaton_operaton&open=AZLdYgMyewFQZUw2mxrH
related to #85
=> refactor: Replace stream.collect(Collectors.toList()) by stream.toList()

engine/pom.xml, engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/UpdateProcessInstancesSuspendStateAsyncTest.java, qa/large-data-tests/pom.xml, qa/large-data-tests/src/test/java/org/operaton/bpm/qa/largedata/util/EngineDataGenerator.java
Resolve usages of the Guava library and remove dependency.
closes #559
=> dependencies: Resolve Guava dependency

.devenv/scripts/maintenance/update-slack-link.sh, .github/scripts/git-commit.sh, .github/workflows/maintenance.yml, .github/workflows/release.yml
Adds a new workflow 'maintenance.yml' that in its first step allows to update the Slack invitation link.
Added scripts to perform the update and reduce the script amount in workflow files (git commit).
related to #561
=> chore(build): Add maintenance workflow & scripts

database/pom.xml, engine/src/main/java/org/operaton/bpm/engine/impl/db/sql/DbSqlSession.java, test-utils/testcontainers/pom.xml, test-utils/testcontainers/src/main/java/org/operaton/impl/test/utils/testcontainers/OperatonOracleContainerProvider.java, test-utils/testcontainers/src/main/resources/META-INF/services/org.testcontainers.containers.JdbcDatabaseContainerProvider
=> Start using Oracle Testcontainer [#553]

engine/src/main/java/org/operaton/bpm/engine/impl/cmd/SetJobRetriesCmd.java
- Rename a static field that had the same name as class member
- Mark unserializable field as transient
related to #511
=> chore: Resolve Sonar findings

engine/src/main/junit5/org/operaton/bpm/engine/test/junit5/ProcessEngineTestExtension.java, engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceCaseInstanceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceCaseTaskTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceHumanTaskTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceMilestoneTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceProcessTaskTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceStageTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceTest.java
=> chore(test): Convert all tests in cmmn package to JUnit5.

bom/internal-dependencies/pom.xml, parent/pom.xml
- Spring 6.2.3 -> 6.2.5
- Spring Boot 3.4.3 -> 3.4.4
=> dependencies: upgrade Spring

qa/performance-tests-engine/pom.xml, qa/performance-tests-engine/src/main/java/org/operaton/bpm/qa/performance/engine/util/JsonUtil.java
=> Resolve dependency on jackson-mapper-asl #656

bom/internal-dependencies/pom.xml
=> dependencies: Removed bouncycastle references

engine/src/main/junit5/org/operaton/bpm/engine/test/junit5/ProcessEngineTestExtension.java, engine/src/test/java/org/operaton/bpm/engine/test/api/filter/FilterAuthorizationsTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/filter/FilterPropertiesTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/filter/FilterQueryTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/filter/FilterServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/filter/FilterServiceUserOperationLogTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/filter/FilterTaskQueryTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/form/BuiltInValidatorsTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/form/FormDataTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/form/FormPropertyDefaultValueTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/form/FormServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/form/HtmlFormEngineTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/form/RetrieveOperatonFormRefTest.java, engine/src/test/java/org/operaton/bpm/engine/test/util/OperatonFormUtils.java
=> chore(test): Convert all tests in filter and form packages.

.devenv/scripts/build/build-and-run-integration-tests.sh, .github/workflows/integration-build.yml, database/pom.xml
=> Upgrade mysql connector

engine-cdi/pom.xml, engine/src/main/junit4/org/operaton/bpm/engine/test/util/ProcessEngineTestRule.java
=> Fix test failures

engine/src/test/java/org/operaton/bpm/engine/test/api/identity/AdminGroupsTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/AdminUsersTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/AuthorizationQueryAuthorizationsTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/AuthorizationQueryTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/AuthorizationServiceAuthorizationsTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/AuthorizationServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/AuthorizationServiceWithEnabledAuthorizationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/CustomPasswordPolicyTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/DatabasePrefixHandlerTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/DefaultAuthorizationProviderTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/GroupQueryTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceAuthorizationsTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceTenantTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceUserOperationLogTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceWithJdbcSimpleProcessingTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/PasswordHashingTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/PasswordPolicyConfigurationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/ReadOnlyIdentityServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/TenantQueryTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/UserQueryTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/WriteMultipleEntitiesInOneTransactionTest.java
=> refactor(tests): Convert all tests in identity package.

bom/internal-dependencies/pom.xml, parent/pom.xml, qa/tomcat-runtime/pom.xml
Added JNA libs to tomcat-runtime
related to #687
=> chore: Fix tomcat postgres integration tests

pom.xml
https://github.com/camunda/camunda-bpm-platform/issues/4902
Backported commit b8055fcea9 from the camunda-bpm-platform repository.
Original author: yanavasileva <yanavasileva@users.noreply.github.com>
=> chore(deps): bump to feel-scala 1.19.1

distro/tomcat/assembly/assembly.xml
=> chore: Avoid duplicate libraries in Tomcat distro

bom/internal-dependencies/pom.xml, distro/wildfly/distro/assembly.xml, distro/wildfly/modules/src/main/modules/org/operaton/bpm/operaton-engine-plugin-spin/main/module.xml, distro/wildfly/modules/src/main/modules/org/operaton/spin/operaton-spin-dataformat-xml-dom/main/module.xml, engine-rest/pom.xml, parent/pom.xml, qa/wildfly-runtime/pom.xml, qa/wildfly-runtime/src/main/common/modules/org/python/jython/main/module.xml, spin/dataformat-json-jackson/pom.xml
This PR fixes integration test on Wildfly & h2 database.
=> Fix wildfly inttests

engine/src/test/java/org/operaton/bpm/engine/test/api/history/BatchHistoricDecisionInstanceDeletionUserOperationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/metrics/AbstractMetricsTest.java, engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorCmdExceptionTest.java, engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorExceptionLoggingHandlerTest.java, engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/ReducedJobExceptionLoggingTest.java
=> fix(tests): Fix flacky tests by avoid caching of engine.

README.md
Remove www from page links for operaton.org
=> Fix web page link issue in Readme

engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ParallelMultiInstanceActivityBehavior.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/SequentialMultiInstanceActivityBehavior.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/multiinstance/MultiInstanceTest.java
related to https://github.com/camunda/camunda-bpm-platform/issues/2082
Co-authored-by: yanavasileva <yanavasileva@users.noreply.github.com>
Backported commit 169d51f3fe from the camunda-bpm-platform repository.
Original author: HuangLiang <1512460987@qq.com>
=> fix(engine): fix multi-instance collection expression evaluation

engine-cdi/src/test/java/org/operaton/bpm/engine/cdi/test/api/annotation/ExecutionIdTest.java, engine-plugins/spin-plugin/src/test/java/org/operaton/spin/plugin/variables/XmlValueTest.java, engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/util/container/EmbeddedServerBootstrap.java, engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/util/container/TomcatServerBootstrap.java, engine/src/main/java/org/operaton/bpm/engine/impl/history/event/HistoryEvent.java, engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/JobExecutor.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricVariableInstanceEntity.java, engine/src/main/java/org/operaton/bpm/engine/impl/pvm/delegate/TaskListener.java, engine/src/main/java/org/operaton/bpm/engine/impl/test/TestHelper.java, engine/src/main/java/org/operaton/bpm/engine/repository/DeploymentQuery.java, engine/src/test/java/org/operaton/bpm/engine/test/api/repository/DeploymentQueryTest.java
Resolve various Sonar findings
=> Code cleanup

webapps/frontend/ui/tasklist/client/scripts/tasklist/directives/cam-tasklist-tasks.js
related to: camunda/camunda-bpm-platform#4793
Backported commit 4a27a64508 from the camunda-bpm-platform repository.
=> fix(webapps/tasklist): render task if no filter exists

engine/src/main/java/org/operaton/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/repository/ProcessApplicationDeploymentBuilderImpl.java, engine/src/main/java/org/operaton/bpm/engine/repository/DeploymentBuilder.java, engine/src/main/java/org/operaton/bpm/engine/repository/ProcessApplicationDeploymentBuilder.java
- fix deprecation javadocs
- mark also overridden methods by subclasses
=> chore: DeploymentBuilder: Mark enableDuplicateFiltering() for removal

spring-boot-starter/starter-webapp-core/src/main/java/org/operaton/bpm/spring/boot/starter/webapp/FaviconResourceResolver.java, spring-boot-starter/starter-webapp-core/src/main/java/org/operaton/bpm/spring/boot/starter/webapp/OperatonBpmWebappAutoConfiguration.java, spring-boot-starter/starter-webapp-core/src/test/java/org/operaton/bpm/spring/boot/starter/webapp/FaviconResourceResolverTest.java, spring-boot-starter/starter-webapp-core/src/test/java/org/operaton/bpm/spring/boot/starter/webapp/OperatonBpmWebappAutoConfigurationIntegrationTest.java
related to: camunda/camunda-bpm-platform/issues/4930
Backported commit dde22ef498 from the camunda-bpm-platform repository.
=> fix(spring-boot-webapp): resolve favicon path

engine/src/main/java/org/operaton/bpm/container/impl/deployment/scanning/ClassPathProcessApplicationScanner.java
Related to camunda/camunda-bpm-platform#4292
Backported commit 493f327cd0 from the camunda-bpm-platform repository.
=> fix(engine): Fix nested jar loading for Spring Boot 3.2

engine-cdi/src/test/java/org/operaton/bpm/engine/cdi/test/api/annotation/ProcessVariableLocalTypedTest.java, engine-cdi/src/test/java/org/operaton/bpm/engine/cdi/test/api/annotation/ProcessVariableTypedTest.java, engine-cdi/src/test/java/org/operaton/bpm/engine/cdi/test/api/annotation/StartProcessTest.java, engine-cdi/src/test/java/org/operaton/bpm/engine/cdi/test/impl/el/BeanPropertyElTest.java, engine-cdi/src/test/java/org/operaton/bpm/engine/cdi/test/impl/event/EventNotificationTest.java
Resolves Sonar findings of type java:S5838
=> chore: use dedicated AssertJ assertion methods

.github/workflows/integration-build.yml
- fix path to resolve property `version.operaton.dbscheme`
- configure override of upload artifact
closes #779
=> Build: Fix integration build

engine-rest/engine-rest-openapi-generator/src/main/java/org/operaton/bpm/engine/rest/openapi/generator/impl/TemplateParser.java, engine-rest/engine-rest-openapi/src/main/templates/main.ftl
=> fix: Update version variable name from 'cambpmVersion' to 'operatonbpmVersion' in TemplateParser and main.ftl

.devenv/scripts/maintenance/update-slack-link.sh, CONTRIBUTING.md, README.md
=> fix(build): Fix replacement of Slack link

commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/impl/type/FileValueTypeImpl.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/impl/value/FileValueImpl.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/impl/value/builder/FileValueBuilderImpl.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/type/FileValueType.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/type/PrimitiveValueType.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/type/SerializableValueType.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/type/ValueType.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/value/BooleanValue.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/value/BytesValue.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/value/DateValue.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/value/DoubleValue.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/value/FileValue.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/value/IntegerValue.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/value/LongValue.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/value/ObjectValue.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/value/PrimitiveValue.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/value/SerializationDataFormat.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/value/ShortValue.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/value/StringValue.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/value/TypedValue.java, commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/value/builder/FileValueBuilder.java
- Remove old since Javadoc tags
related to #797
=> docs: Remove old since Javadoc tags

spin/core/src/main/java/org/operaton/spin/spi/DataFormatMapper.java, spin/core/src/main/java/org/operaton/spin/spi/DataFormatWriter.java, spin/dataformat-xml-dom/src/main/java/org/operaton/spin/impl/xml/dom/format/spi/JaxBContextProvider.java
=> chore(spin): Unnecessary Modifier

model-api/cmmn-model/src/main/java/org/operaton/bpm/model/cmmn/instance/IfPart.java
=> chore(model-api): Unnecessary Modifier

commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/type/ValueType.java, commons/utils/src/main/java/org/operaton/commons/utils/cache/Cache.java
=> chore(commons): Unnecessary Modifier

webapps/assembly/src/main/java/org/operaton/bpm/cockpit/CockpitRuntimeDelegate.java, webapps/assembly/src/main/java/org/operaton/bpm/cockpit/plugin/PluginRegistry.java, webapps/assembly/src/main/java/org/operaton/bpm/cockpit/plugin/spi/CockpitPlugin.java, webapps/assembly/src/main/java/org/operaton/bpm/webapp/AppRuntimeDelegate.java, webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/security/SecurityActions.java, webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/security/filter/RequestAuthorizer.java, webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/security/filter/SecurityFilterRule.java, webapps/assembly/src/main/java/org/operaton/bpm/webapp/plugin/AppPluginRegistry.java, webapps/assembly/src/main/java/org/operaton/bpm/webapp/plugin/resource/PluginResourceOverride.java, webapps/assembly/src/main/java/org/operaton/bpm/webapp/plugin/spi/AppPlugin.java
=> chore(webapps): Unnecessary Modifier

juel/src/main/java/org/operaton/bpm/impl/juel/AstBinary.java, juel/src/main/java/org/operaton/bpm/impl/juel/AstUnary.java, juel/src/main/java/org/operaton/bpm/impl/juel/ExpressionFactoryImpl.java, juel/src/main/java/org/operaton/bpm/impl/juel/ExpressionNode.java, juel/src/main/java/org/operaton/bpm/impl/juel/FunctionNode.java, juel/src/main/java/org/operaton/bpm/impl/juel/IdentifierNode.java, juel/src/main/java/org/operaton/bpm/impl/juel/Node.java, juel/src/main/java/org/operaton/bpm/impl/juel/TreeBuilder.java, juel/src/main/java/org/operaton/bpm/impl/juel/TreeCache.java, juel/src/main/java/org/operaton/bpm/impl/juel/TypeConverter.java
=> chore(juel): Unnecessary Modifier

.devenv/scripts/tools/list-unique-dependencies.sh, bom/internal-dependencies/pom.xml, parent/pom.xml
- Update to SpringBoot 3.5.0
- Update to Spring 6.2.7
closes #827
=> Upgrade SpringBoot & Spring

engine-rest/engine-rest-openapi-generator/src/main/java/org/operaton/bpm/engine/rest/openapi/generator/impl/TemplateParser.java, engine/src/main/java/org/operaton/bpm/engine/impl/HistoricCaseActivityInstanceQueryImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/db/sql/DbSqlSession.java, engine/src/main/java/org/operaton/bpm/engine/impl/history/event/HistoricDecisionInstanceManager.java, engine/src/main/java/org/operaton/bpm/engine/impl/interceptor/BpmnStackTrace.java, engine/src/main/java/org/operaton/bpm/engine/impl/json/JsonTaskQueryConverter.java, engine/src/main/java/org/operaton/bpm/engine/impl/optimize/OptimizeManager.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/deploy/cache/CaseDefinitionCache.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/deploy/cache/DecisionDefinitionCache.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/deploy/cache/OperatonFormDefinitionCache.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/deploy/cache/ProcessDefinitionCache.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/AuthorizationManager.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/EventSubscriptionManager.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/FilterEntity.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ResourceManager.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/UserOperationLogManager.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/VariableInstanceManager.java, engine/src/main/java/org/operaton/bpm/engine/impl/repository/DeploymentBuilderImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/util/ScriptUtil.java, examples/invoice/src/main/java/org/operaton/bpm/example/invoice/DemoDataGenerator.java, examples/invoice/src/main/java/org/operaton/bpm/example/invoice/InvoiceApplicationHelper.java, juel/src/main/java/org/operaton/bpm/impl/juel/AstIdentifier.java, juel/src/main/java/org/operaton/bpm/impl/juel/AstProperty.java, juel/src/main/java/org/operaton/bpm/impl/juel/TypeConverterImpl.java
=> String deduplication

distro/run/core/src/main/java/org/operaton/bpm/run/OperatonBpmRunDeploymentConfiguration.java
This should fix the sonar issue java:S4507.
=> fix: Replaced printStackTrace with a log message

engine/src/main/java/org/operaton/bpm/container/impl/spi/ServiceTypes.java, engine/src/main/java/org/operaton/bpm/engine/authorization/OptimizePermissions.java, engine/src/main/java/org/operaton/bpm/engine/authorization/Permissions.java, engine/src/main/java/org/operaton/bpm/engine/authorization/ProcessDefinitionPermissions.java, engine/src/main/java/org/operaton/bpm/engine/authorization/ProcessInstancePermissions.java, engine/src/main/java/org/operaton/bpm/engine/authorization/SystemPermissions.java, engine/src/main/java/org/operaton/bpm/engine/authorization/UserOperationLogCategoryPermissions.java, engine/src/main/java/org/operaton/bpm/engine/impl/core/model/BaseCallableElement.java, engine/src/main/java/org/operaton/bpm/engine/impl/history/event/HistoryEventTypes.java, engine/src/main/java/org/operaton/bpm/engine/repository/ResourceTypes.java, engine/src/test/java/org/operaton/bpm/container/impl/jmx/kernel/util/TestServiceType.java, engine/src/test/java/org/operaton/bpm/engine/test/api/identity/TestPermissions.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/local/bean/BusinessInterface.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/local/bean/StartProcessInterface.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/remote/bean/BusinessInterface.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/request/beans/InvocationCounterService.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/request/beans/InvocationCounterServiceLocal.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/scriptengine/engine/AbstractScriptEngineFactory.java, spring-boot-starter/starter-webapp-core/src/main/java/org/operaton/bpm/spring/boot/starter/webapp/filter/LazyDelegateFilter.java, spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/configuration/Ordering.java
Performed code cleanup with IJ
closes #821
=> chore: Remove redundant modifiers

engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/diagram/ProcessDiagramLayoutFactory.java, engine/src/main/java/org/operaton/bpm/engine/impl/util/ResourceTypeUtil.java, juel/src/main/java/org/operaton/bpm/impl/juel/SimpleResolver.java, webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/security/filter/headersec/HttpHeaderSecurityFilter.java
Resolves Sonar issues of type
Double Brace Initialization should not be used java:S3599
related to #511
=> chore: Avoid Double-Brace-Initialization

engine/src/main/java/org/operaton/bpm/engine/history/HistoricProcessInstanceQuery.java, engine/src/main/java/org/operaton/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java, engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml, engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceTest.java, engine/src/test/resources/org/operaton/bpm/engine/test/api/history/testInstancesWithJobsRetrying.bpmn20.xml
related to camunda/camunda-bpm-platform#4904
Backported commit 22c50da015 from the camunda-bpm-platform repository.
Original author: Helene <21290204+PHWaechtler@users.noreply.github.com>
=> feat(queryAPI): add filter for instances with jobs retrying in java API

bom/internal-dependencies/pom.xml
Resolves a vulnerability in spring-web.
See https://github.com/operaton/operaton/security/dependabot/317
=> build(deps): Upgrade to Spring 6.2.8

engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/execution/CaseExecutionImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/handler/CmmnHandlerContext.java, engine/src/main/java/org/operaton/bpm/engine/impl/db/PermissionCheck.java, engine/src/main/java/org/operaton/bpm/engine/impl/dmn/entity/repository/DecisionDefinitionEntity.java, engine/src/main/java/org/operaton/bpm/engine/impl/history/event/HistoricFormPropertyEventEntity.java, engine/src/main/java/org/operaton/bpm/engine/impl/interceptor/TxContextCommandContextFactory.java, engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupJobHandlerConfiguration.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ExecutionEntity.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/IncidentStatisticsEntity.java, engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/ExecutionImpl.java, engine/src/main/java/org/operaton/bpm/engine/management/TablePage.java, jakarta-ee/jobexecutor-ra/src/main/java/org/operaton/bpm/container/impl/threading/ra/outbound/JcaExecutorServiceManagedConnectionFactory.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/cdi/beans/RetryConfig.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/context/classes/MyPojo.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/dataformat/CustomDataFormatConfigurator.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spring/beans/RetryConfig.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/classes/MyPojo.java, spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/property/EventingProperty.java
=> refactor: Remove empty default constructors

engine/src/main/java/org/operaton/bpm/engine/impl/db/entitymanager/DbEntityManager.java, engine/src/main/java/org/operaton/bpm/engine/impl/interceptor/Session.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/AbstractManager.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/DeploymentManager.java
Remove empty implementations
related to #400
=> refactor: Make methods of Session empty default methods

webapps/frontend/public/app/admin/locales/de.json, webapps/frontend/public/app/admin/locales/en.json, webapps/frontend/ui/admin/client/scripts/pages/execution-metrics.html, webapps/frontend/ui/admin/client/scripts/pages/execution-metrics.js
related to camunda/camunda-bpm-platform/issues/4415
Backported commit 203dc2592c from the camunda-bpm-platform repository.
=> task(webapp): execution metrics page, adjust month column (#5033)

webapps/frontend/public/app/cockpit/locales/de.json, webapps/frontend/public/app/cockpit/locales/en.json
related to: /camunda/camunda-bpm-platform/issues/4906
Backported commit c829dd5494 from the camunda-bpm-platform repository.
=> feat(webapps): localisation for instances with jobs retrying (#4959)

webapps/frontend/public/app/cockpit/scripts/config.js, webapps/frontend/ui/cockpit/client/scripts/repository/deployments/plugins/actions/delete/modals/cam-cockpit-delete-deployment-modal-ctrl.js, webapps/frontend/ui/common/scripts/services/cam-configuration.js
Related to https://github.com/camunda/camunda-bpm-platform/issues/2479
Backported commit d14135f52d from the camunda-bpm-platform repository.
=> feat(cockpit): Make default value for cascade flag configurable (#4964)

webapps/frontend/operaton-commons-ui/lib/widgets/inline-field/dialog/controller.js
related to: camunda/camunda-bpm-platform/issues/4955
Backported commit 0c9ce58ebf from the camunda-bpm-platform repository.
=> feat(webapps): auto format expanded edit field (#4963)

engine/src/main/java/org/operaton/bpm/engine/impl/batch/BatchMonitorJobHandler.java, engine/src/main/java/org/operaton/bpm/engine/impl/batch/BatchSeedJobHandler.java, engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/AsyncContinuationJobHandler.java, engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/JobHandler.java, engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/ProcessEventJobHandler.java, engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/TimerChangeJobDefinitionSuspensionStateJobHandler.java, engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/TimerChangeProcessDefinitionSuspensionStateJobHandler.java, engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/TimerEventJobHandler.java, engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupJobHandler.java, engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/TweetExceptionHandler.java, engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/TweetHandler.java, engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/TweetNestedCommandExceptionHandler.java
=> refactor: Make JobHandler#onDelete default method

parent/pom.xml, pom.xml
This change performs the upgrade of SpringBoot 3.5.0 to 3.5.3.
=> build(deps): bump SpringBoot version to 3.5.3

engine/src/test/junit5/org/operaton/bpm/engine/impl/calendar/CronExpressionTest.java
This change adds a unit test for class `CronExpression`.
closes #751 
closes #767
=> Add unit test for CronExpression

distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/Attribute.java, distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/Element.java, distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/ModelConstants.java, distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/Namespace.java, distro/wildfly/subsystem/src/test/java/org/operaton/bpm/container/impl/jboss/test/JBossSubsystemXMLTest.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetDeploymentResourceForIdCmd.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetDeploymentResourcesCmd.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetTaskAttachmentCmd.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetTaskAttachmentContentCmd.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetTaskCommentCmd.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmd/PatchTaskVariablesCmd.java, engine/src/main/java/org/operaton/bpm/engine/repository/Resource.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/FailingJobBoundaryTimerWithDelegateVariablesTest.java
refactor: fix @author comment sections with redundant replacements
- rolls back redundant changes in @author comment sections from @operaton.com to @camunda.com
closes #960
=> refactor: Fix @author redundant @camunda.com -> @operaton.com replacements

database/pom.xml, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/util/ArquillianEventObserver.java, qa/tomcat-runtime/pom.xml, qa/wildfly-runtime/pom.xml, qa/wildfly-runtime/src/main/common/modules/com/mysql/mysql-connector-j/main/module.xml, qa/wildfly-runtime/src/main/common/standalone/deployments/mysql-ds.xml, qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml, test-utils/testcontainers/src/test/java/org/operaton/impl/test/utils/testcontainers/DatabaseContainerProviderTest.java
=> fix: Enable MySQL Tests on Wildfly and Tomcat

engine-cdi/src/test/java/org/operaton/bpm/engine/cdi/test/impl/context/ThreadContextAssociationTest.java, engine-cdi/src/test/java/org/operaton/bpm/engine/cdi/test/impl/event/EventNotificationTest.java, engine/src/main/junit-shared/org/operaton/bpm/engine/test/util/JobExecutorAssert.java, engine/src/main/junit-shared/org/operaton/bpm/engine/test/util/JobExecutorWaitUtils.java
Adapt test code accordingy.
relates to #803
=> feat(test): add fluent JobExecutor assertion.

engine/src/main/java/org/operaton/bpm/engine/impl/HistoricDecisionInstanceStatisticsQueryImpl.java, engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoricDecisionInstanceStatisticsQueryTest.java
Add decisionInstanceId null check
- add processInstanceId property null check
- enable related test
closes #438
=> Fix HistoricDecisionInstanceStatisticsQuery should throws NullValueException

test-utils/testcontainers/src/main/java/org/operaton/impl/test/utils/testcontainers/OperatonMySqlContainerProvider.java
See https://docs.operaton.org/docs/documentation/user-guide/process-engine/database/mysql-configuration/#jdbc-driver-configuration
=> fix(test): Use the recommended connection parameters for MySQL

.github/workflows/build.yml, CONTRIBUTING.md, NOTICE, README.md, docs/decisions/.markdownlint.yml, docs/decisions/README.md, docs/decisions/adr-template.md
This PR introduces a structured framework for documenting architectural decisions using Architectural Decision Records (ADRs). It includes:
- An ADR template (`adr-template.md`) based on MADR format.
- A detailed README explaining when and how to use ADRs.
- Updates to the `CONTRIBUTING.md`, `README.md`, and `NOTICE` files to reflect ADR usage.
- A markdownlint GitHub Action workflow for ADRs.
Closes #979
Establishing consistent architectural documentation ensures traceability, improves onboarding for new contributors, and supports maintainable long-term architecture. ADRs will help document significant design decisions, their reasoning, and context.
- Introduced `docs/decisions/adr-template.md` using MADR structure.
- Created `docs/decisions/README.md` outlining when and how to write …
=> feat: add ADR template and README for architectural decisions

engine/src/test/java/org/operaton/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupHelperTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/cfg/IdGeneratorDataSourceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/repository/RepositoryServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/deployment/BpmnDeploymentTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/signal/SignalEventConcurrencyTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/parse/GlobalRetryConfigurationStandardTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/parse/GlobalRetryConfigurationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/property/PropertyTest.java, engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/DeploymentAwareJobExecutorTest.java, engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobAcquisitionLoggingTest.java, engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorFollowUpTest.java, engine/src/test/java/org/operaton/bpm/engine/test/standalone/deploy/DeploymentTest.java, engine/src/test/java/org/operaton/bpm/engine/test/standalone/history/HistoryCleanupBatchTest.java
=> refactor(test): Migrate remaining tests in engine to JUnit5.

engine-cdi/src/main/java/org/operaton/bpm/engine/cdi/jsf/TaskForm.java, engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/dto/authorization/AuthorizationQueryDtoTest.java, engine-spring/src/main/java/org/operaton/bpm/engine/spring/components/aop/ProcessStartingMethodInterceptor.java, engine/src/main/java/org/operaton/bpm/container/impl/ContainerIntegrationLogger.java, engine/src/main/java/org/operaton/bpm/engine/ProcessEngines.java, engine/src/main/java/org/operaton/bpm/engine/impl/ant/LaunchThread.java, engine/src/main/java/org/operaton/bpm/engine/impl/calendar/CronExpression.java, engine/src/main/java/org/operaton/bpm/engine/impl/cmd/DeployCmd.java, engine/src/main/java/org/operaton/bpm/engine/impl/form/type/EnumFormType.java, engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/operation/PvmAtomicOperationTransitionDestroyScope.java, engine/src/main/java/org/operaton/bpm/engine/impl/util/LogUtil.java, engine/src/main/java/org/operaton/bpm/engine/impl/util/xml/Parse.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/deployment/BpmnDeploymentTest.java, engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/DeploymentAwareJobExecutorTest.java, engine/src/test/java/org/operaton/bpm/engine/test/standalone/history/FullHistoryTest.java, juel/src/main/java/org/operaton/bpm/impl/juel/AstBinary.java, juel/src/main/java/org/operaton/bpm/impl/juel/AstChoice.java, juel/src/main/java/org/operaton/bpm/impl/juel/AstMethod.java, model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/ReferenceTest.java, test-utils/assert/core/src/main/java/org/operaton/bpm/engine/test/assertions/bpmn/ProcessInstanceAssert.java, test-utils/assert/core/src/main/java/org/operaton/bpm/engine/test/assertions/cmmn/AbstractCaseAssert.java, webapps/assembly/src/main/java/org/operaton/bpm/cockpit/impl/plugin/base/sub/resources/ProcessDefinitionResource.java, webapps/assembly/src/main/java/org/operaton/bpm/cockpit/impl/plugin/resources/ProcessInstanceRestService.java, webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/filter/AbstractTemplateFilter.java, webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/security/auth/Authentications.java, webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/security/filter/CsrfPreventionFilter.java, webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/authorization/AuthorizationTest.java, webapps/assembly/src/test/java/org/operaton/bpm/webapp/impl/filter/TemplateFilterTest.java, webapps/assembly/src/test/java/org/operaton/bpm/webapp/impl/security/filter/csrf/CsrfPreventionFilterAppPathTest.java
This PR contains refactorings to address multiple Sonar findings.
See the individual commits for changes.
=> Resolve sonar issues

bom/internal-dependencies/pom.xml, engine-rest/engine-rest/pom.xml, parent/pom.xml, webapps/assembly/pom.xml
Upgrade from Tomcat 10.1.42 to 11.0.9. Centralized the Tomcat version in parent POM.
related to #909
=> build(dependencis): Upgrade to Tomcat 11.0.9

distro/tomcat/distro/assembly.xml, engine/src/main/resources/META-INF/services/jakarta.servlet.ServletContainerInitializer
This change fixes the Tomcat distro. It also upgrades to Tomcat 11.0.9.
closes #1011
=> Fix Tomcat distro

clients/java/client/pom.xml, distro/tomcat/distro/pom.xml, qa/integration-tests-webapps/shared-engine/pom.xml
=> chore: Update Tomcat container id to tomcat11x

engine/src/main/java/org/operaton/bpm/application/impl/ServletProcessApplication.java, examples/invoice/src/main/java/org/operaton/bpm/example/invoice/InvoiceProcessApplication.java
This reverts c8e1735edbf475bf21b2c41366e100b914292735
The annotation lead to duplicate registration of the InvoiceProcessApplication as listener.
=> fix(tomcat): Remove WebListener annotation

spin/core/pom.xml, spin/dataformat-json-jackson/pom.xml, spin/dataformat-json-jackson/src/test/java/org/operaton/spin/json/tree/JsonJacksonTreeNodeTest.java, spin/dataformat-json-jackson/src/test/java/org/operaton/spin/json/tree/JsonTreeMapJavaToJsonTest.java, spin/dataformat-json-jackson/src/test/java/org/operaton/spin/json/tree/JsonTreeMapObjectToJsonScriptTest.java, spin/pom.xml
=> refactor(tests-dep): replace JsonFluentAssert by AssertJ

pom.xml
=> chore(build): Ignore JRuby 10 for versions-maven-plugin

engine-rest/engine-rest/pom.xml
Resolves MadeYouReset DDoS vulnerability
=> chore(deps): Upgrade netty-all & undertow

database/pom.xml, pom.xml
Streamline version between liquibase-maven-plugin and liquibase dependency by moving version.liquibase to Root POM
=> chore(deps): Upgrade Liquibase to 4.33.0

engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java, engine/src/main/java/org/operaton/bpm/engine/impl/core/model/Properties.java, engine/src/main/java/org/operaton/bpm/engine/impl/core/model/PropertyKey.java, engine/src/main/java/org/operaton/bpm/engine/impl/core/model/PropertyListKey.java, engine/src/main/java/org/operaton/bpm/engine/impl/core/model/PropertyMapKey.java, engine/src/main/java/org/operaton/bpm/engine/impl/event/EventHandlerImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/externaltask/LockedExternalTaskImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ExternalTaskEntity.java, engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/operation/PvmAtomicOperationCancelActivity.java, engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/operation/PvmAtomicOperationCreateConcurrentExecution.java
Closes https://github.com/operaton/operaton/issues/1055
=> refactor(class-to-record): Refactor Property*Key classes to records

.devenv/scripts/build/build.sh
=> chore(build): Temporary disable dependency analysis report (#1095)

webapps/frontend/package-lock.json, webapps/frontend/package.json
closes [1108](https://github.com/operaton/operaton/issues/1108)
=> Upgrade eslint-plugin-i18n-json from 4.0.0 to 4.0.1

engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java
closes [1120](https://github.com/operaton/operaton/issues/1120)
=> Refactor codebase to replace deprecated isEqualToIgnoringMinutes with isCloseTo

webapps/frontend/package-lock.json, webapps/frontend/package.json
- Remove extract-loader from devDependencies and clean up package-lock.json.
- Verified build process and project functionality remain intact.
**Affected files:** 
- webapps/frontend/package-lock.json
- webapps/frontend/package.json
closes #1125
=> refactor(frontend): remove unused extract-loader dependency

engine-rest/engine-rest-openapi/src/main/templates/paths/process-definition/{id}/delete.ftl
=> chore(rest): fix deleteProcessDefinition description [#1166]

clients/java/client/src/main/java/org/operaton/bpm/client/interceptor/impl/RequestInterceptorHandler.java, engine-spring/src/main/java/org/operaton/bpm/engine/spring/components/aop/ActivitiStateAnnotationBeanPostProcessor.java, engine/src/main/java/org/operaton/bpm/engine/ProcessEngines.java, engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java, engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/RuntimeServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricExternalTaskLogTest.java
This PR resolves several Sonar warnings.
=> Cleanup: Resolve sonar warnings

engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/optimize/OptimizeCompletedHistoricIncidentRestServiceTest.java, engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/optimize/OptimizeOpenHistoricIncidentRestServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/IncidentTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ExecutionQueryTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceModificationAsyncTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskQueryTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/message/MessageBoundaryEventTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/shell/ShellTaskTest.java, engine/src/test/java/org/operaton/bpm/engine/test/standalone/pvm/ActivityInstanceVerification.java
=> Junit4 Assert to AssertJ

engine/src/main/java/org/operaton/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
I confirm that my contribution and following ones comply with the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0)
and the [Code of Conduct](https://github.com/operaton/operaton/blob/main/CODE_OF_CONDUCT.md).
=> Backport "fix(db2): update to modern pagination for DB2"

engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java
=> Backport "fix(engine) Add space in validateServiceTaskLike error message (#5357)"

distro/run/core/src/test/java/org/operaton/bpm/run/test/util/LoggingInterceptor.java, distro/run/qa/integration-tests/src/test/java/org/operaton/bpm/run/qa/util/SpringBootManagedContainer.java, engine-cdi/src/main/java/org/operaton/bpm/engine/cdi/impl/util/CreationalContextReleaseListener.java, engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/DefaultUserPermissionNameForTaskCfgTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoryServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/mail/EmailTestCase.java, engine/src/test/java/org/operaton/bpm/engine/test/cmmn/operation/CaseExecutionStateTransitionCollector.java, engine/src/test/java/org/operaton/bpm/engine/test/concurrency/AbstractCompetingTransactionsOptimisticLockingTest.java, engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingActivityInstanceCancellationTest.java, engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingForkTest.java, engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingJobAcquisitionTest.java, engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingJoinTest.java, engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingParentCompletionTest.java, engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingProcessCompletionTest.java, engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingSentrySatisfactionTest.java, engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingSignalsTest.java, engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingSubprocessCompletionTest.java, engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingSuspensionTest.java, engine/src/test/java/org/operaton/bpm/engine/test/concurrency/ConcurrentVariableUpdateTest.java, engine/src/test/java/org/operaton/bpm/engine/test/concurrency/ControllableThread.java, engine/src/test/java/org/operaton/bpm/engine/test/logging/LogEngineNameDelegate.java, engine/src/test/java/org/operaton/bpm/engine/test/standalone/pvm/EventCollector.java, engine/src/test/java/org/operaton/bpm/engine/test/standalone/pvm/activities/ParallelGateway.java
=> refactor(logging): Refactor logging arguments with concatenated strings

engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-instance.ftl, engine-rest/engine-rest-openapi/src/main/templates/lib/commons/process-instance-query-params.ftl, engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java, engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/runtime/ProcessInstanceQueryDto.java, engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/ProcessInstanceRestServiceQueryTest.java, engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/helper/MockProvider.java, engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricProcessInstanceRestServiceQueryTest.java, engine/src/main/java/org/operaton/bpm/engine/history/HistoricProcessInstanceQuery.java, engine/src/main/java/org/operaton/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/ProcessInstanceQueryImpl.java, engine/src/main/java/org/operaton/bpm/engine/runtime/ProcessInstanceQuery.java, engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/Execution.xml, engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml, engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceQueryTest.java, engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceTest.java
=> feat(api): filter process instances by rootProcessInstanceId [#1162]

pom.xml
- [Changelog](https://github.com/quarkusio/quarkus/releases/tag/3.26.2)
=> build(deps): bump Quarkus 3.26.1 -> 3.26.2

engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/Resource.xml, engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/MultiTenancyRepositoryServiceTest.java
=> Backport camunda 3366f1b467

distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/service/MscExecutorService.java
Also rename variable enhancedQueueExecutor
Fixes #1263
=> fix(wildfly): MscExecutorService has to update lastWarningLogged after logging

bom/internal-dependencies/pom.xml, distro/run/qa/integration-tests/pom.xml, distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/handler/JobExecutorAdd.java, parent/pom.xml, qa/integration-tests-webapps/integration-tests/pom.xml, qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/AbstractWebIntegrationTest.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/AbstractWebappUiIntegrationTest.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/CsrfPreventionIT.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/DateSerializationIT.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/ErrorPageIT.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/ExceptionLoggerIT.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/HttpHeaderSecurityIT.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/PluginsRootResourceIT.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/SessionCookieSameSiteIT.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/SessionCookieSecurityIT.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/TestProperties.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/rest/RestIT.java, qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/rest/RestJaxRs2IT.java, qa/integration-tests-webapps/pom.xml, spring-boot-starter/starter-qa/integration-test-webapp/runtime/pom.xml, spring-boot-starter/starter/src/test/java/org/operaton/bpm/spring/boot/starter/configuration/impl/DefaultDatasourceConfigurationTest.java
Backport commit https://github.com/camunda/camunda-bpm-platform/commit/d8f5129907
closes #1175
=> Resolve HTTPClient 4 dependency

engine/src/main/junit-shared/org/operaton/bpm/engine/impl/test/TestHelper.java, engine/src/test/java/org/operaton/bpm/engine/impl/test/TestHelperTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/IncidentTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/JobEntityTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/JobQueryTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/resources/HistoryByteArrayTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/resources/RuntimeByteArrayTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/async/FoxJobRetryCmdTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/async/JobRetryCmdWithDefaultPropertyTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/timer/BoundaryTimerNonInterruptingEventTest.java, engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java, engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricJobLogTest.java, engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceStateTest.java, engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorCmdExceptionTest.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/context/SetVariablesMigrationContextSwitchTest.java, test-utils/assert/core/src/test/java/org/operaton/bpm/engine/test/assertions/bpmn/JobAssertHasExceptionMessageTest.java
=> refactor(tests): standardize executeJob calls with expect-exception helper

.github/workflows/check-for-new-contributor.yml
I confirm that my contribution and following ones comply with the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0)
and the [Code of Conduct](https://github.com/operaton/operaton/blob/main/CODE_OF_CONDUCT.md)
=> ci: add workflow to greet first-time contributors

qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/transactions/TransactionIntegrationTest.java
This is the only remaining pattern I could find that uses AssertJ
- Progresses #564
=> refactor(tests): Replace try/catch with expected failure in test code

.github/jreleaser/changelog.tpl
Updated changelog file for jReleaser.
=> Updated jreleaser changelog for Quarkus upgrade.

engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/GroupRestService.java, engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/authorization/AuthorizationResource.java, engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/identity/GroupResource.java, engine/src/main/java/org/operaton/bpm/engine/impl/db/DbIdGenerator.java, engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricExternalTaskLogManager.java, engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java, engine/src/main/java/org/operaton/bpm/engine/impl/util/EnsureUtil.java, engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/HistoricRootProcessInstanceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceTest.java, engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/query/history/MultiTenancyHistoricExternalTaskLogTest.java, engine/src/test/java/org/operaton/bpm/engine/test/cmmn/sentry/SentryVariableOnPartEntryCriteriaTest.java, engine/src/test/java/org/operaton/bpm/engine/test/standalone/calendar/DurationHelperTest.java, engine/src/test/java/org/operaton/bpm/engine/test/standalone/db/SchemaLogEnsureSqlScriptTest.java, engine/src/test/java/org/operaton/bpm/engine/test/util/ObjectProperty.java, juel/src/main/java/org/operaton/bpm/impl/juel/Parser.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/impl/instance/ExtensionImpl.java, model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/instance/Extension.java, model-api/cmmn-model/src/test/java/org/operaton/bpm/model/cmmn10/Cmmn10Test.java, qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/beans/DemoDelegate.java, test-utils/assert/core/src/test/java/org/operaton/bpm/engine/test/assertions/cmmn/CaseInstanceAssertTest.java, webapps/assembly/src/test/java/org/operaton/bpm/webapp/impl/security/auth/AuthCacheTest.java
- Rename variables to solve "Local variable and method parameter names should comply with a naming convention"
related to operaton#511
=> chore: Fix Sonar findings about naming convention

bom/internal-dependencies/pom.xml, engine-plugins/identity-ldap/pom.xml, engine-rest/engine-rest/pom.xml, engine-spring/pom.xml, engine/pom.xml, parent/pom.xml, qa/test-db-instance-migration/pom.xml, qa/test-db-instance-migration/test-fixture-719/pom.xml, qa/test-old-engine/pom.xml
- Remove unused dependencies
- order internal dependencies
- move dependency declarations that are only used in qa modules to there
=> chore(deps): Dependency management
